include "../core/types.fbs";
include "view_direction.fbs";

namespace steamrot;

table SocketConfigFbs {
  socket_count: int = 0;
  radius: float = 10.0;
  min_gap: float = 0.0;
  fixed_socket_angle: float = 0.0;
  has_fixed_socket: bool = false;
  rotation_arc_min: float = 0.0;
  rotation_arc_max: float = 360.0;
}

table JointFbs{
  name: string (required);
  origin: Vector2fDataFbs (required);
  socket_config: SocketConfigFbs (required);
  positioning_views: [ViewFbs] (required);
}

root_type JointFbs;

