include "../core/types.fbs";
include "../core/data_population_function.fbs";
include "../events/subscriber.fbs";
include "../events/event_packet.fbs";

namespace steamrot;


enum LayoutFbs: byte{ 
  None = 0,
  Horizontal = 1,
  Vertical = 2,
  Grid = 3,
  DropDown = 4,

  }

enum SpacingAndSizingFbs: byte {
    None = 0,
    Even = 1,
    Ratioed = 2,
    DropDownList = 3,
  }


union UIElementDataUnionFbs {
  PanelDataFbs,
  ButtonDataFbs,
  DropDownListDataFbs,
  DropDownContainerDataFbs,
  DropDownItemDataFbs,
  DropDownButtonDataFbs
}

table ChildDataFbs {
  element: UIElementDataUnionFbs (required);
}

table UIElementDataFbs{
    position: Vector2fDataFbs (required);
    size: Vector2fDataFbs (required);
    subscriber_data: SubscriberFbs;
    response_event_data: [EventPacketFbs];
    children_active: bool ;
    children: [ChildDataFbs] (required);
    is_mouse_over: bool;
    layout: LayoutFbs;
    spacing_strategy: SpacingAndSizingFbs;
  }
table PanelDataFbs{  base_data: UIElementDataFbs(required);}

table ButtonDataFbs {
  base_data: UIElementDataFbs(required);
 label: string (required);
}

table DropDownContainerDataFbs{
  base_data: UIElementDataFbs(required);

  }


table DropDownListDataFbs{
  base_data: UIElementDataFbs(required);
    unexpanded_label: string;
    expanded_label: string ;
    data_population_function: DataPopulationFunctionFbs;
  }

table DropDownItemDataFbs {
  base_data: UIElementDataFbs(required);
    label: string (required);

  }

table DropDownButtonDataFbs {
  base_data: UIElementDataFbs(required);
    is_expanded: bool;
  }




table UserInterfaceFbs{
  // first structure must be a PanelElement
    root_ui_element: PanelDataFbs (required); 
    ui_name: string; 
    is_visible: bool;
    priority: int;
  }

root_type UserInterfaceFbs;
