if(EXISTS "/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/logic/test_logic_tests-b12d07c.cmake")
  include("/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/logic/test_logic_tests-b12d07c.cmake")
else()
  add_test(test_logic_NOT_BUILT-b12d07c test_logic_NOT_BUILT-b12d07c)
endif()
