if(EXISTS "/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/integration/scene_change/test_scene_change_tests-b12d07c.cmake")
  include("/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/integration/scene_change/test_scene_change_tests-b12d07c.cmake")
else()
  add_test(test_scene_change_NOT_BUILT-b12d07c test_scene_change_NOT_BUILT-b12d07c)
endif()
