////////////////////////////////////////////////////////////
/// @file
/// @brief FlatBuffers schema for EventContext.
///
/// EventContextFbs contains the lifetime information for events
/// managed by the EventHandler.
////////////////////////////////////////////////////////////

namespace steamrot;

////////////////////////////////////////////////////////////
/// Event context data
////////////////////////////////////////////////////////////
table EventContextFbs {
  /// Lifetime of the event (ticked down by 1 each tick)
  lifetime: ubyte = 1;
}
