include "event_packet.fbs";

namespace steamrot;

table SubscriberFbs{


////////////////////////////////////////////////////////////
/// EventTypeFbs enum value
////////////////////////////////////////////////////////////
  event_type: EventTypeFbs;


////////////////////////////////////////////////////////////
/// any one of the EventPayloadFbs union, used to determine if the Subscriber should be activated
////////////////////////////////////////////////////////////
  filter_payload: EventPayloadFbs (required);
  
  }
