if(EXISTS "/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/data_handlers/test_data_handlers_tests-b12d07c.cmake")
  include("/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/data_handlers/test_data_handlers_tests-b12d07c.cmake")
else()
  add_test(test_data_handlers_NOT_BUILT-b12d07c test_data_handlers_NOT_BUILT-b12d07c)
endif()
