if(EXISTS "/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/systems/test_systems_tests-b12d07c.cmake")
  include("/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/systems/test_systems_tests-b12d07c.cmake")
else()
  add_test(test_systems_NOT_BUILT-b12d07c test_systems_NOT_BUILT-b12d07c)
endif()
