// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ACTIONS_STEAMROT_H_
#define FLATBUFFERS_GENERATED_ACTIONS_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace steamrot {

struct Action;
struct ActionBuilder;

struct ActionsData;
struct ActionsDataBuilder;

enum KeyboardInput : uint8_t {
  KeyboardInput_A = 0,
  KeyboardInput_B = 1,
  KeyboardInput_C = 2,
  KeyboardInput_D = 3,
  KeyboardInput_E = 4,
  KeyboardInput_F = 5,
  KeyboardInput_G = 6,
  KeyboardInput_H = 7,
  KeyboardInput_I = 8,
  KeyboardInput_J = 9,
  KeyboardInput_K = 10,
  KeyboardInput_L = 11,
  KeyboardInput_M = 12,
  KeyboardInput_N = 13,
  KeyboardInput_O = 14,
  KeyboardInput_P = 15,
  KeyboardInput_Q = 16,
  KeyboardInput_R = 17,
  KeyboardInput_S = 18,
  KeyboardInput_T = 19,
  KeyboardInput_U = 20,
  KeyboardInput_V = 21,
  KeyboardInput_W = 22,
  KeyboardInput_X = 23,
  KeyboardInput_Y = 24,
  KeyboardInput_Z = 25,
  KeyboardInput_MIN = KeyboardInput_A,
  KeyboardInput_MAX = KeyboardInput_Z
};

inline const KeyboardInput (&EnumValuesKeyboardInput())[26] {
  static const KeyboardInput values[] = {
    KeyboardInput_A,
    KeyboardInput_B,
    KeyboardInput_C,
    KeyboardInput_D,
    KeyboardInput_E,
    KeyboardInput_F,
    KeyboardInput_G,
    KeyboardInput_H,
    KeyboardInput_I,
    KeyboardInput_J,
    KeyboardInput_K,
    KeyboardInput_L,
    KeyboardInput_M,
    KeyboardInput_N,
    KeyboardInput_O,
    KeyboardInput_P,
    KeyboardInput_Q,
    KeyboardInput_R,
    KeyboardInput_S,
    KeyboardInput_T,
    KeyboardInput_U,
    KeyboardInput_V,
    KeyboardInput_W,
    KeyboardInput_X,
    KeyboardInput_Y,
    KeyboardInput_Z
  };
  return values;
}

inline const char * const *EnumNamesKeyboardInput() {
  static const char * const names[27] = {
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    nullptr
  };
  return names;
}

inline const char *EnumNameKeyboardInput(KeyboardInput e) {
  if (::flatbuffers::IsOutRange(e, KeyboardInput_A, KeyboardInput_Z)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesKeyboardInput()[index];
}

enum MouseInput : uint8_t {
  MouseInput_LEFT_CLICK = 0,
  MouseInput_RIGHT_CLICK = 1,
  MouseInput_MIDDLE_CLICK = 2,
  MouseInput_SCROLL_UP = 3,
  MouseInput_SCROLL_DOWN = 4,
  MouseInput_MIN = MouseInput_LEFT_CLICK,
  MouseInput_MAX = MouseInput_SCROLL_DOWN
};

inline const MouseInput (&EnumValuesMouseInput())[5] {
  static const MouseInput values[] = {
    MouseInput_LEFT_CLICK,
    MouseInput_RIGHT_CLICK,
    MouseInput_MIDDLE_CLICK,
    MouseInput_SCROLL_UP,
    MouseInput_SCROLL_DOWN
  };
  return values;
}

inline const char * const *EnumNamesMouseInput() {
  static const char * const names[6] = {
    "LEFT_CLICK",
    "RIGHT_CLICK",
    "MIDDLE_CLICK",
    "SCROLL_UP",
    "SCROLL_DOWN",
    nullptr
  };
  return names;
}

inline const char *EnumNameMouseInput(MouseInput e) {
  if (::flatbuffers::IsOutRange(e, MouseInput_LEFT_CLICK, MouseInput_SCROLL_DOWN)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMouseInput()[index];
}

enum ActionNames : uint64_t {
  ActionNames_ACTION_NONE = 1ULL,
  ActionNames_ACTION_CHANGE_SCENE = 2ULL,
  ActionNames_NONE = 0,
  ActionNames_ANY = 3ULL
};

inline const ActionNames (&EnumValuesActionNames())[2] {
  static const ActionNames values[] = {
    ActionNames_ACTION_NONE,
    ActionNames_ACTION_CHANGE_SCENE
  };
  return values;
}

inline const char * const *EnumNamesActionNames() {
  static const char * const names[3] = {
    "ACTION_NONE",
    "ACTION_CHANGE_SCENE",
    nullptr
  };
  return names;
}

inline const char *EnumNameActionNames(ActionNames e) {
  if (::flatbuffers::IsOutRange(e, ActionNames_ACTION_NONE, ActionNames_ACTION_CHANGE_SCENE)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(ActionNames_ACTION_NONE);
  return EnumNamesActionNames()[index];
}

struct Action FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEYBOARD_PRESSED = 4,
    VT_KEYBOARD_RELEASED = 6,
    VT_MOUSE_PRESSED = 8,
    VT_MOUSE_RELEASED = 10,
    VT_ACTION_NAME = 12
  };
  const ::flatbuffers::Vector<uint8_t> *keyboard_pressed() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_KEYBOARD_PRESSED);
  }
  const ::flatbuffers::Vector<uint8_t> *keyboard_released() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_KEYBOARD_RELEASED);
  }
  const ::flatbuffers::Vector<uint8_t> *mouse_pressed() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_MOUSE_PRESSED);
  }
  const ::flatbuffers::Vector<uint8_t> *mouse_released() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_MOUSE_RELEASED);
  }
  steamrot::ActionNames action_name() const {
    return static_cast<steamrot::ActionNames>(GetField<uint64_t>(VT_ACTION_NAME, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEYBOARD_PRESSED) &&
           verifier.VerifyVector(keyboard_pressed()) &&
           VerifyOffset(verifier, VT_KEYBOARD_RELEASED) &&
           verifier.VerifyVector(keyboard_released()) &&
           VerifyOffset(verifier, VT_MOUSE_PRESSED) &&
           verifier.VerifyVector(mouse_pressed()) &&
           VerifyOffset(verifier, VT_MOUSE_RELEASED) &&
           verifier.VerifyVector(mouse_released()) &&
           VerifyField<uint64_t>(verifier, VT_ACTION_NAME, 8) &&
           verifier.EndTable();
  }
};

struct ActionBuilder {
  typedef Action Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_keyboard_pressed(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> keyboard_pressed) {
    fbb_.AddOffset(Action::VT_KEYBOARD_PRESSED, keyboard_pressed);
  }
  void add_keyboard_released(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> keyboard_released) {
    fbb_.AddOffset(Action::VT_KEYBOARD_RELEASED, keyboard_released);
  }
  void add_mouse_pressed(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> mouse_pressed) {
    fbb_.AddOffset(Action::VT_MOUSE_PRESSED, mouse_pressed);
  }
  void add_mouse_released(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> mouse_released) {
    fbb_.AddOffset(Action::VT_MOUSE_RELEASED, mouse_released);
  }
  void add_action_name(steamrot::ActionNames action_name) {
    fbb_.AddElement<uint64_t>(Action::VT_ACTION_NAME, static_cast<uint64_t>(action_name), 0);
  }
  explicit ActionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Action> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Action>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Action> CreateAction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> keyboard_pressed = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> keyboard_released = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> mouse_pressed = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> mouse_released = 0,
    steamrot::ActionNames action_name = static_cast<steamrot::ActionNames>(0)) {
  ActionBuilder builder_(_fbb);
  builder_.add_action_name(action_name);
  builder_.add_mouse_released(mouse_released);
  builder_.add_mouse_pressed(mouse_pressed);
  builder_.add_keyboard_released(keyboard_released);
  builder_.add_keyboard_pressed(keyboard_pressed);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Action> CreateActionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *keyboard_pressed = nullptr,
    const std::vector<uint8_t> *keyboard_released = nullptr,
    const std::vector<uint8_t> *mouse_pressed = nullptr,
    const std::vector<uint8_t> *mouse_released = nullptr,
    steamrot::ActionNames action_name = static_cast<steamrot::ActionNames>(0)) {
  auto keyboard_pressed__ = keyboard_pressed ? _fbb.CreateVector<uint8_t>(*keyboard_pressed) : 0;
  auto keyboard_released__ = keyboard_released ? _fbb.CreateVector<uint8_t>(*keyboard_released) : 0;
  auto mouse_pressed__ = mouse_pressed ? _fbb.CreateVector<uint8_t>(*mouse_pressed) : 0;
  auto mouse_released__ = mouse_released ? _fbb.CreateVector<uint8_t>(*mouse_released) : 0;
  return steamrot::CreateAction(
      _fbb,
      keyboard_pressed__,
      keyboard_released__,
      mouse_pressed__,
      mouse_released__,
      action_name);
}

struct ActionsData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ActionsDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACTIONS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::Action>> *actions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::Action>> *>(VT_ACTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACTIONS) &&
           verifier.VerifyVector(actions()) &&
           verifier.VerifyVectorOfTables(actions()) &&
           verifier.EndTable();
  }
};

struct ActionsDataBuilder {
  typedef ActionsData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_actions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::Action>>> actions) {
    fbb_.AddOffset(ActionsData::VT_ACTIONS, actions);
  }
  explicit ActionsDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ActionsData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ActionsData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ActionsData> CreateActionsData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::Action>>> actions = 0) {
  ActionsDataBuilder builder_(_fbb);
  builder_.add_actions(actions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ActionsData> CreateActionsDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<steamrot::Action>> *actions = nullptr) {
  auto actions__ = actions ? _fbb.CreateVector<::flatbuffers::Offset<steamrot::Action>>(*actions) : 0;
  return steamrot::CreateActionsData(
      _fbb,
      actions__);
}

inline const steamrot::ActionsData *GetActionsData(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::ActionsData>(buf);
}

inline const steamrot::ActionsData *GetSizePrefixedActionsData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::ActionsData>(buf);
}

inline bool VerifyActionsDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::ActionsData>(nullptr);
}

inline bool VerifySizePrefixedActionsDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::ActionsData>(nullptr);
}

inline void FinishActionsDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::ActionsData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedActionsDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::ActionsData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_ACTIONS_STEAMROT_H_
