// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONTEXTDATA_STEAMROT_H_
#define FLATBUFFERS_GENERATED_CONTEXTDATA_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "scene_change_packet_generated.h"

namespace steamrot {

struct GameContextConfig;
struct GameContextConfigBuilder;

struct SceneContextConfig;
struct SceneContextConfigBuilder;

struct ContextData;
struct ContextDataBuilder;

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
struct GameContextConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GameContextConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WINDOW_WIDTH = 4,
    VT_WINDOW_HEIGHT = 6,
    VT_WINDOW_TITLE = 8,
    VT_FRAMERATE_LIMIT = 10,
    VT_ENVIRONMENT_TYPE = 12
  };
  uint32_t window_width() const {
    return GetField<uint32_t>(VT_WINDOW_WIDTH, 800);
  }
  uint32_t window_height() const {
    return GetField<uint32_t>(VT_WINDOW_HEIGHT, 600);
  }
  const ::flatbuffers::String *window_title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_WINDOW_TITLE);
  }
  uint32_t framerate_limit() const {
    return GetField<uint32_t>(VT_FRAMERATE_LIMIT, 60);
  }
  const ::flatbuffers::String *environment_type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENVIRONMENT_TYPE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_WINDOW_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_WINDOW_HEIGHT, 4) &&
           VerifyOffset(verifier, VT_WINDOW_TITLE) &&
           verifier.VerifyString(window_title()) &&
           VerifyField<uint32_t>(verifier, VT_FRAMERATE_LIMIT, 4) &&
           VerifyOffset(verifier, VT_ENVIRONMENT_TYPE) &&
           verifier.VerifyString(environment_type()) &&
           verifier.EndTable();
  }
};

struct GameContextConfigBuilder {
  typedef GameContextConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_window_width(uint32_t window_width) {
    fbb_.AddElement<uint32_t>(GameContextConfig::VT_WINDOW_WIDTH, window_width, 800);
  }
  void add_window_height(uint32_t window_height) {
    fbb_.AddElement<uint32_t>(GameContextConfig::VT_WINDOW_HEIGHT, window_height, 600);
  }
  void add_window_title(::flatbuffers::Offset<::flatbuffers::String> window_title) {
    fbb_.AddOffset(GameContextConfig::VT_WINDOW_TITLE, window_title);
  }
  void add_framerate_limit(uint32_t framerate_limit) {
    fbb_.AddElement<uint32_t>(GameContextConfig::VT_FRAMERATE_LIMIT, framerate_limit, 60);
  }
  void add_environment_type(::flatbuffers::Offset<::flatbuffers::String> environment_type) {
    fbb_.AddOffset(GameContextConfig::VT_ENVIRONMENT_TYPE, environment_type);
  }
  explicit GameContextConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GameContextConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GameContextConfig>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GameContextConfig> CreateGameContextConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t window_width = 800,
    uint32_t window_height = 600,
    ::flatbuffers::Offset<::flatbuffers::String> window_title = 0,
    uint32_t framerate_limit = 60,
    ::flatbuffers::Offset<::flatbuffers::String> environment_type = 0) {
  GameContextConfigBuilder builder_(_fbb);
  builder_.add_environment_type(environment_type);
  builder_.add_framerate_limit(framerate_limit);
  builder_.add_window_title(window_title);
  builder_.add_window_height(window_height);
  builder_.add_window_width(window_width);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GameContextConfig> CreateGameContextConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t window_width = 800,
    uint32_t window_height = 600,
    const char *window_title = nullptr,
    uint32_t framerate_limit = 60,
    const char *environment_type = nullptr) {
  auto window_title__ = window_title ? _fbb.CreateString(window_title) : 0;
  auto environment_type__ = environment_type ? _fbb.CreateString(environment_type) : 0;
  return steamrot::CreateGameContextConfig(
      _fbb,
      window_width,
      window_height,
      window_title__,
      framerate_limit,
      environment_type__);
}

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
struct SceneContextConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneContextConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCENE_TYPE = 4,
    VT_ENTITY_POOL_SIZE = 6,
    VT_RENDER_TEXTURE_WIDTH = 8,
    VT_RENDER_TEXTURE_HEIGHT = 10
  };
  steamrot::SceneType scene_type() const {
    return static_cast<steamrot::SceneType>(GetField<int8_t>(VT_SCENE_TYPE, 0));
  }
  uint32_t entity_pool_size() const {
    return GetField<uint32_t>(VT_ENTITY_POOL_SIZE, 100);
  }
  uint32_t render_texture_width() const {
    return GetField<uint32_t>(VT_RENDER_TEXTURE_WIDTH, 800);
  }
  uint32_t render_texture_height() const {
    return GetField<uint32_t>(VT_RENDER_TEXTURE_HEIGHT, 600);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_SCENE_TYPE, 1) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_POOL_SIZE, 4) &&
           VerifyField<uint32_t>(verifier, VT_RENDER_TEXTURE_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_RENDER_TEXTURE_HEIGHT, 4) &&
           verifier.EndTable();
  }
};

struct SceneContextConfigBuilder {
  typedef SceneContextConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_scene_type(steamrot::SceneType scene_type) {
    fbb_.AddElement<int8_t>(SceneContextConfig::VT_SCENE_TYPE, static_cast<int8_t>(scene_type), 0);
  }
  void add_entity_pool_size(uint32_t entity_pool_size) {
    fbb_.AddElement<uint32_t>(SceneContextConfig::VT_ENTITY_POOL_SIZE, entity_pool_size, 100);
  }
  void add_render_texture_width(uint32_t render_texture_width) {
    fbb_.AddElement<uint32_t>(SceneContextConfig::VT_RENDER_TEXTURE_WIDTH, render_texture_width, 800);
  }
  void add_render_texture_height(uint32_t render_texture_height) {
    fbb_.AddElement<uint32_t>(SceneContextConfig::VT_RENDER_TEXTURE_HEIGHT, render_texture_height, 600);
  }
  explicit SceneContextConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneContextConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneContextConfig>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneContextConfig> CreateSceneContextConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    steamrot::SceneType scene_type = steamrot::SceneType_UNKNOWN,
    uint32_t entity_pool_size = 100,
    uint32_t render_texture_width = 800,
    uint32_t render_texture_height = 600) {
  SceneContextConfigBuilder builder_(_fbb);
  builder_.add_render_texture_height(render_texture_height);
  builder_.add_render_texture_width(render_texture_width);
  builder_.add_entity_pool_size(entity_pool_size);
  builder_.add_scene_type(scene_type);
  return builder_.Finish();
}

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
struct ContextData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ContextDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GAME_CONTEXT = 4,
    VT_SCENE_CONTEXTS = 6
  };
  const steamrot::GameContextConfig *game_context() const {
    return GetPointer<const steamrot::GameContextConfig *>(VT_GAME_CONTEXT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SceneContextConfig>> *scene_contexts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SceneContextConfig>> *>(VT_SCENE_CONTEXTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_GAME_CONTEXT) &&
           verifier.VerifyTable(game_context()) &&
           VerifyOffset(verifier, VT_SCENE_CONTEXTS) &&
           verifier.VerifyVector(scene_contexts()) &&
           verifier.VerifyVectorOfTables(scene_contexts()) &&
           verifier.EndTable();
  }
};

struct ContextDataBuilder {
  typedef ContextData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_game_context(::flatbuffers::Offset<steamrot::GameContextConfig> game_context) {
    fbb_.AddOffset(ContextData::VT_GAME_CONTEXT, game_context);
  }
  void add_scene_contexts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SceneContextConfig>>> scene_contexts) {
    fbb_.AddOffset(ContextData::VT_SCENE_CONTEXTS, scene_contexts);
  }
  explicit ContextDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ContextData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ContextData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ContextData> CreateContextData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::GameContextConfig> game_context = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SceneContextConfig>>> scene_contexts = 0) {
  ContextDataBuilder builder_(_fbb);
  builder_.add_scene_contexts(scene_contexts);
  builder_.add_game_context(game_context);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ContextData> CreateContextDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::GameContextConfig> game_context = 0,
    const std::vector<::flatbuffers::Offset<steamrot::SceneContextConfig>> *scene_contexts = nullptr) {
  auto scene_contexts__ = scene_contexts ? _fbb.CreateVector<::flatbuffers::Offset<steamrot::SceneContextConfig>>(*scene_contexts) : 0;
  return steamrot::CreateContextData(
      _fbb,
      game_context,
      scene_contexts__);
}

inline const steamrot::ContextData *GetContextData(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::ContextData>(buf);
}

inline const steamrot::ContextData *GetSizePrefixedContextData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::ContextData>(buf);
}

inline bool VerifyContextDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::ContextData>(nullptr);
}

inline bool VerifySizePrefixedContextDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::ContextData>(nullptr);
}

inline void FinishContextDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::ContextData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedContextDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::ContextData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_CONTEXTDATA_STEAMROT_H_
