namespace steamrot;

////////////////////////////////////////////////////////////
// Configuration for Engine core settings
////////////////////////////////////////////////////////////
table EngineCoreData {
  window_width: uint32 = 800;
  window_height: uint32 = 600;
  window_title: string;
  framerate_limit: uint32 = 60;
}

////////////////////////////////////////////////////////////
// Configuration for a scene's core settings
////////////////////////////////////////////////////////////
table SceneCoreData {
  render_texture_width: uint32 = 800;
  render_texture_height: uint32 = 600;
}
