// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENGINEDATA_STEAMROT_H_
#define FLATBUFFERS_GENERATED_ENGINEDATA_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "event_bus_data_generated.h"
#include "resource_data_generated.h"
#include "scene_manager_data_generated.h"
#include "subscriber_data_generated.h"

namespace steamrot {

struct EngineData;
struct EngineDataBuilder;

struct EngineData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EngineDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBSCRIPTIONS = 4,
    VT_GAME_RESOURCES = 6,
    VT_SCENE_MANAGER_DATA = 8,
    VT_GLOBAL_EVENT_BUS_DATA = 10,
    VT_WAITING_ROOM_EVENT_BUS_DATA = 12
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>> *subscriptions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>> *>(VT_SUBSCRIPTIONS);
  }
  const steamrot::GameResourcesData *game_resources() const {
    return GetPointer<const steamrot::GameResourcesData *>(VT_GAME_RESOURCES);
  }
  const steamrot::SceneManagerData *scene_manager_data() const {
    return GetPointer<const steamrot::SceneManagerData *>(VT_SCENE_MANAGER_DATA);
  }
  const steamrot::EventBusData *global_event_bus_data() const {
    return GetPointer<const steamrot::EventBusData *>(VT_GLOBAL_EVENT_BUS_DATA);
  }
  const steamrot::EventBusData *waiting_room_event_bus_data() const {
    return GetPointer<const steamrot::EventBusData *>(VT_WAITING_ROOM_EVENT_BUS_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SUBSCRIPTIONS) &&
           verifier.VerifyVector(subscriptions()) &&
           verifier.VerifyVectorOfTables(subscriptions()) &&
           VerifyOffset(verifier, VT_GAME_RESOURCES) &&
           verifier.VerifyTable(game_resources()) &&
           VerifyOffset(verifier, VT_SCENE_MANAGER_DATA) &&
           verifier.VerifyTable(scene_manager_data()) &&
           VerifyOffset(verifier, VT_GLOBAL_EVENT_BUS_DATA) &&
           verifier.VerifyTable(global_event_bus_data()) &&
           VerifyOffset(verifier, VT_WAITING_ROOM_EVENT_BUS_DATA) &&
           verifier.VerifyTable(waiting_room_event_bus_data()) &&
           verifier.EndTable();
  }
};

struct EngineDataBuilder {
  typedef EngineData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_subscriptions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>>> subscriptions) {
    fbb_.AddOffset(EngineData::VT_SUBSCRIPTIONS, subscriptions);
  }
  void add_game_resources(::flatbuffers::Offset<steamrot::GameResourcesData> game_resources) {
    fbb_.AddOffset(EngineData::VT_GAME_RESOURCES, game_resources);
  }
  void add_scene_manager_data(::flatbuffers::Offset<steamrot::SceneManagerData> scene_manager_data) {
    fbb_.AddOffset(EngineData::VT_SCENE_MANAGER_DATA, scene_manager_data);
  }
  void add_global_event_bus_data(::flatbuffers::Offset<steamrot::EventBusData> global_event_bus_data) {
    fbb_.AddOffset(EngineData::VT_GLOBAL_EVENT_BUS_DATA, global_event_bus_data);
  }
  void add_waiting_room_event_bus_data(::flatbuffers::Offset<steamrot::EventBusData> waiting_room_event_bus_data) {
    fbb_.AddOffset(EngineData::VT_WAITING_ROOM_EVENT_BUS_DATA, waiting_room_event_bus_data);
  }
  explicit EngineDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EngineData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EngineData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EngineData> CreateEngineData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>>> subscriptions = 0,
    ::flatbuffers::Offset<steamrot::GameResourcesData> game_resources = 0,
    ::flatbuffers::Offset<steamrot::SceneManagerData> scene_manager_data = 0,
    ::flatbuffers::Offset<steamrot::EventBusData> global_event_bus_data = 0,
    ::flatbuffers::Offset<steamrot::EventBusData> waiting_room_event_bus_data = 0) {
  EngineDataBuilder builder_(_fbb);
  builder_.add_waiting_room_event_bus_data(waiting_room_event_bus_data);
  builder_.add_global_event_bus_data(global_event_bus_data);
  builder_.add_scene_manager_data(scene_manager_data);
  builder_.add_game_resources(game_resources);
  builder_.add_subscriptions(subscriptions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EngineData> CreateEngineDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<steamrot::SubscriberData>> *subscriptions = nullptr,
    ::flatbuffers::Offset<steamrot::GameResourcesData> game_resources = 0,
    ::flatbuffers::Offset<steamrot::SceneManagerData> scene_manager_data = 0,
    ::flatbuffers::Offset<steamrot::EventBusData> global_event_bus_data = 0,
    ::flatbuffers::Offset<steamrot::EventBusData> waiting_room_event_bus_data = 0) {
  auto subscriptions__ = subscriptions ? _fbb.CreateVector<::flatbuffers::Offset<steamrot::SubscriberData>>(*subscriptions) : 0;
  return steamrot::CreateEngineData(
      _fbb,
      subscriptions__,
      game_resources,
      scene_manager_data,
      global_event_bus_data,
      waiting_room_event_bus_data);
}

inline const steamrot::EngineData *GetEngineData(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::EngineData>(buf);
}

inline const steamrot::EngineData *GetSizePrefixedEngineData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::EngineData>(buf);
}

inline bool VerifyEngineDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::EngineData>(nullptr);
}

inline bool VerifySizePrefixedEngineDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::EngineData>(nullptr);
}

inline void FinishEngineDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::EngineData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEngineDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::EngineData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_ENGINEDATA_STEAMROT_H_
