// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENGINESTATE_STEAMROT_H_
#define FLATBUFFERS_GENERATED_ENGINESTATE_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "subscriber_data_generated.h"

namespace steamrot {

struct EngineStateFbs;
struct EngineStateFbsBuilder;

////////////////////////////////////////////////////////////
/// Engine runtime state configuration
////////////////////////////////////////////////////////////
struct EngineStateFbs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EngineStateFbsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RUNNING = 4,
    VT_PAUSED = 6,
    VT_SUBSCRIPTIONS = 8,
    VT_QUIT_REQUESTED = 10
  };
  /// Initial running state
  bool running() const {
    return GetField<uint8_t>(VT_RUNNING, 0) != 0;
  }
  /// Initial paused state
  bool paused() const {
    return GetField<uint8_t>(VT_PAUSED, 0) != 0;
  }
  /// Engine-level subscribers (e.g., quit game handler)
  const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>> *subscriptions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>> *>(VT_SUBSCRIPTIONS);
  }
  /// Initial quit requested state
  bool quit_requested() const {
    return GetField<uint8_t>(VT_QUIT_REQUESTED, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_RUNNING, 1) &&
           VerifyField<uint8_t>(verifier, VT_PAUSED, 1) &&
           VerifyOffset(verifier, VT_SUBSCRIPTIONS) &&
           verifier.VerifyVector(subscriptions()) &&
           verifier.VerifyVectorOfTables(subscriptions()) &&
           VerifyField<uint8_t>(verifier, VT_QUIT_REQUESTED, 1) &&
           verifier.EndTable();
  }
};

struct EngineStateFbsBuilder {
  typedef EngineStateFbs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_running(bool running) {
    fbb_.AddElement<uint8_t>(EngineStateFbs::VT_RUNNING, static_cast<uint8_t>(running), 0);
  }
  void add_paused(bool paused) {
    fbb_.AddElement<uint8_t>(EngineStateFbs::VT_PAUSED, static_cast<uint8_t>(paused), 0);
  }
  void add_subscriptions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>>> subscriptions) {
    fbb_.AddOffset(EngineStateFbs::VT_SUBSCRIPTIONS, subscriptions);
  }
  void add_quit_requested(bool quit_requested) {
    fbb_.AddElement<uint8_t>(EngineStateFbs::VT_QUIT_REQUESTED, static_cast<uint8_t>(quit_requested), 0);
  }
  explicit EngineStateFbsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EngineStateFbs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EngineStateFbs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EngineStateFbs> CreateEngineStateFbs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool running = false,
    bool paused = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>>> subscriptions = 0,
    bool quit_requested = false) {
  EngineStateFbsBuilder builder_(_fbb);
  builder_.add_subscriptions(subscriptions);
  builder_.add_quit_requested(quit_requested);
  builder_.add_paused(paused);
  builder_.add_running(running);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EngineStateFbs> CreateEngineStateFbsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool running = false,
    bool paused = false,
    const std::vector<::flatbuffers::Offset<steamrot::SubscriberData>> *subscriptions = nullptr,
    bool quit_requested = false) {
  auto subscriptions__ = subscriptions ? _fbb.CreateVector<::flatbuffers::Offset<steamrot::SubscriberData>>(*subscriptions) : 0;
  return steamrot::CreateEngineStateFbs(
      _fbb,
      running,
      paused,
      subscriptions__,
      quit_requested);
}

inline const steamrot::EngineStateFbs *GetEngineStateFbs(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::EngineStateFbs>(buf);
}

inline const steamrot::EngineStateFbs *GetSizePrefixedEngineStateFbs(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::EngineStateFbs>(buf);
}

inline bool VerifyEngineStateFbsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::EngineStateFbs>(nullptr);
}

inline bool VerifySizePrefixedEngineStateFbsBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::EngineStateFbs>(nullptr);
}

inline void FinishEngineStateFbsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::EngineStateFbs> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEngineStateFbsBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::EngineStateFbs> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_ENGINESTATE_STEAMROT_H_
