// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GRIMOIREMACHINA_STEAMROT_H_
#define FLATBUFFERS_GENERATED_GRIMOIREMACHINA_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "fragments_generated.h"

namespace steamrot {

struct GrimoireMachina;
struct GrimoireMachinaBuilder;

struct GrimoireMachina FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GrimoireMachinaBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FRAGMENTS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::FragmentData>> *fragments() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::FragmentData>> *>(VT_FRAGMENTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_FRAGMENTS) &&
           verifier.VerifyVector(fragments()) &&
           verifier.VerifyVectorOfTables(fragments()) &&
           verifier.EndTable();
  }
};

struct GrimoireMachinaBuilder {
  typedef GrimoireMachina Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fragments(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::FragmentData>>> fragments) {
    fbb_.AddOffset(GrimoireMachina::VT_FRAGMENTS, fragments);
  }
  explicit GrimoireMachinaBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GrimoireMachina> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GrimoireMachina>(end);
    fbb_.Required(o, GrimoireMachina::VT_FRAGMENTS);
    return o;
  }
};

inline ::flatbuffers::Offset<GrimoireMachina> CreateGrimoireMachina(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::FragmentData>>> fragments = 0) {
  GrimoireMachinaBuilder builder_(_fbb);
  builder_.add_fragments(fragments);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GrimoireMachina> CreateGrimoireMachinaDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<steamrot::FragmentData>> *fragments = nullptr) {
  auto fragments__ = fragments ? _fbb.CreateVector<::flatbuffers::Offset<steamrot::FragmentData>>(*fragments) : 0;
  return steamrot::CreateGrimoireMachina(
      _fbb,
      fragments__);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_GRIMOIREMACHINA_STEAMROT_H_
