// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RESOURCEDATA_STEAMROT_H_
#define FLATBUFFERS_GENERATED_RESOURCEDATA_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "scene_data_generated.h"

namespace steamrot {

struct GameResourcesData;
struct GameResourcesDataBuilder;

struct SceneResourcesData;
struct SceneResourcesDataBuilder;

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
struct GameResourcesData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GameResourcesDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WINDOW_WIDTH = 4,
    VT_WINDOW_HEIGHT = 6,
    VT_WINDOW_TITLE = 8,
    VT_FRAMERATE_LIMIT = 10
  };
  uint32_t window_width() const {
    return GetField<uint32_t>(VT_WINDOW_WIDTH, 800);
  }
  uint32_t window_height() const {
    return GetField<uint32_t>(VT_WINDOW_HEIGHT, 600);
  }
  const ::flatbuffers::String *window_title() const {
    return GetPointer<const ::flatbuffers::String *>(VT_WINDOW_TITLE);
  }
  uint32_t framerate_limit() const {
    return GetField<uint32_t>(VT_FRAMERATE_LIMIT, 60);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_WINDOW_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_WINDOW_HEIGHT, 4) &&
           VerifyOffset(verifier, VT_WINDOW_TITLE) &&
           verifier.VerifyString(window_title()) &&
           VerifyField<uint32_t>(verifier, VT_FRAMERATE_LIMIT, 4) &&
           verifier.EndTable();
  }
};

struct GameResourcesDataBuilder {
  typedef GameResourcesData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_window_width(uint32_t window_width) {
    fbb_.AddElement<uint32_t>(GameResourcesData::VT_WINDOW_WIDTH, window_width, 800);
  }
  void add_window_height(uint32_t window_height) {
    fbb_.AddElement<uint32_t>(GameResourcesData::VT_WINDOW_HEIGHT, window_height, 600);
  }
  void add_window_title(::flatbuffers::Offset<::flatbuffers::String> window_title) {
    fbb_.AddOffset(GameResourcesData::VT_WINDOW_TITLE, window_title);
  }
  void add_framerate_limit(uint32_t framerate_limit) {
    fbb_.AddElement<uint32_t>(GameResourcesData::VT_FRAMERATE_LIMIT, framerate_limit, 60);
  }
  explicit GameResourcesDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GameResourcesData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GameResourcesData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GameResourcesData> CreateGameResourcesData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t window_width = 800,
    uint32_t window_height = 600,
    ::flatbuffers::Offset<::flatbuffers::String> window_title = 0,
    uint32_t framerate_limit = 60) {
  GameResourcesDataBuilder builder_(_fbb);
  builder_.add_framerate_limit(framerate_limit);
  builder_.add_window_title(window_title);
  builder_.add_window_height(window_height);
  builder_.add_window_width(window_width);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GameResourcesData> CreateGameResourcesDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t window_width = 800,
    uint32_t window_height = 600,
    const char *window_title = nullptr,
    uint32_t framerate_limit = 60) {
  auto window_title__ = window_title ? _fbb.CreateString(window_title) : 0;
  return steamrot::CreateGameResourcesData(
      _fbb,
      window_width,
      window_height,
      window_title__,
      framerate_limit);
}

////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
struct SceneResourcesData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneResourcesDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RENDER_TEXTURE_WIDTH = 4,
    VT_RENDER_TEXTURE_HEIGHT = 6
  };
  uint32_t render_texture_width() const {
    return GetField<uint32_t>(VT_RENDER_TEXTURE_WIDTH, 800);
  }
  uint32_t render_texture_height() const {
    return GetField<uint32_t>(VT_RENDER_TEXTURE_HEIGHT, 600);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_RENDER_TEXTURE_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_RENDER_TEXTURE_HEIGHT, 4) &&
           verifier.EndTable();
  }
};

struct SceneResourcesDataBuilder {
  typedef SceneResourcesData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_render_texture_width(uint32_t render_texture_width) {
    fbb_.AddElement<uint32_t>(SceneResourcesData::VT_RENDER_TEXTURE_WIDTH, render_texture_width, 800);
  }
  void add_render_texture_height(uint32_t render_texture_height) {
    fbb_.AddElement<uint32_t>(SceneResourcesData::VT_RENDER_TEXTURE_HEIGHT, render_texture_height, 600);
  }
  explicit SceneResourcesDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneResourcesData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneResourcesData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneResourcesData> CreateSceneResourcesData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t render_texture_width = 800,
    uint32_t render_texture_height = 600) {
  SceneResourcesDataBuilder builder_(_fbb);
  builder_.add_render_texture_height(render_texture_height);
  builder_.add_render_texture_width(render_texture_width);
  return builder_.Finish();
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_RESOURCEDATA_STEAMROT_H_
