// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SAVEDATA_STEAMROT_H_
#define FLATBUFFERS_GENERATED_SAVEDATA_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "entities_generated.h"
#include "event_bus_data_generated.h"
#include "scene_types_generated.h"

namespace steamrot {

struct SaveMetadata;
struct SaveMetadataBuilder;

struct SaveData;
struct SaveDataBuilder;

////////////////////////////////////////////////////////////
/// Metadata for save file management
////////////////////////////////////////////////////////////
struct SaveMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SaveMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SAVE_NAME = 4,
    VT_CREATED_AT = 6,
    VT_LAST_MODIFIED = 8,
    VT_GAME_VERSION = 10,
    VT_PLAY_TIME_SECONDS = 12,
    VT_SLOT_INDEX = 14
  };
  /// Display name for the save slot
  const ::flatbuffers::String *save_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SAVE_NAME);
  }
  /// Timestamp when save was created (ISO 8601 format)
  const ::flatbuffers::String *created_at() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CREATED_AT);
  }
  /// Timestamp when save was last modified (ISO 8601 format)
  const ::flatbuffers::String *last_modified() const {
    return GetPointer<const ::flatbuffers::String *>(VT_LAST_MODIFIED);
  }
  /// Game version that created this save
  const ::flatbuffers::String *game_version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_GAME_VERSION);
  }
  /// Total play time in seconds
  uint64_t play_time_seconds() const {
    return GetField<uint64_t>(VT_PLAY_TIME_SECONDS, 0);
  }
  /// Save slot identifier (0-based index)
  uint32_t slot_index() const {
    return GetField<uint32_t>(VT_SLOT_INDEX, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SAVE_NAME) &&
           verifier.VerifyString(save_name()) &&
           VerifyOffset(verifier, VT_CREATED_AT) &&
           verifier.VerifyString(created_at()) &&
           VerifyOffset(verifier, VT_LAST_MODIFIED) &&
           verifier.VerifyString(last_modified()) &&
           VerifyOffset(verifier, VT_GAME_VERSION) &&
           verifier.VerifyString(game_version()) &&
           VerifyField<uint64_t>(verifier, VT_PLAY_TIME_SECONDS, 8) &&
           VerifyField<uint32_t>(verifier, VT_SLOT_INDEX, 4) &&
           verifier.EndTable();
  }
};

struct SaveMetadataBuilder {
  typedef SaveMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_save_name(::flatbuffers::Offset<::flatbuffers::String> save_name) {
    fbb_.AddOffset(SaveMetadata::VT_SAVE_NAME, save_name);
  }
  void add_created_at(::flatbuffers::Offset<::flatbuffers::String> created_at) {
    fbb_.AddOffset(SaveMetadata::VT_CREATED_AT, created_at);
  }
  void add_last_modified(::flatbuffers::Offset<::flatbuffers::String> last_modified) {
    fbb_.AddOffset(SaveMetadata::VT_LAST_MODIFIED, last_modified);
  }
  void add_game_version(::flatbuffers::Offset<::flatbuffers::String> game_version) {
    fbb_.AddOffset(SaveMetadata::VT_GAME_VERSION, game_version);
  }
  void add_play_time_seconds(uint64_t play_time_seconds) {
    fbb_.AddElement<uint64_t>(SaveMetadata::VT_PLAY_TIME_SECONDS, play_time_seconds, 0);
  }
  void add_slot_index(uint32_t slot_index) {
    fbb_.AddElement<uint32_t>(SaveMetadata::VT_SLOT_INDEX, slot_index, 0);
  }
  explicit SaveMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SaveMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SaveMetadata>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SaveMetadata> CreateSaveMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> save_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> created_at = 0,
    ::flatbuffers::Offset<::flatbuffers::String> last_modified = 0,
    ::flatbuffers::Offset<::flatbuffers::String> game_version = 0,
    uint64_t play_time_seconds = 0,
    uint32_t slot_index = 0) {
  SaveMetadataBuilder builder_(_fbb);
  builder_.add_play_time_seconds(play_time_seconds);
  builder_.add_slot_index(slot_index);
  builder_.add_game_version(game_version);
  builder_.add_last_modified(last_modified);
  builder_.add_created_at(created_at);
  builder_.add_save_name(save_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SaveMetadata> CreateSaveMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *save_name = nullptr,
    const char *created_at = nullptr,
    const char *last_modified = nullptr,
    const char *game_version = nullptr,
    uint64_t play_time_seconds = 0,
    uint32_t slot_index = 0) {
  auto save_name__ = save_name ? _fbb.CreateString(save_name) : 0;
  auto created_at__ = created_at ? _fbb.CreateString(created_at) : 0;
  auto last_modified__ = last_modified ? _fbb.CreateString(last_modified) : 0;
  auto game_version__ = game_version ? _fbb.CreateString(game_version) : 0;
  return steamrot::CreateSaveMetadata(
      _fbb,
      save_name__,
      created_at__,
      last_modified__,
      game_version__,
      play_time_seconds,
      slot_index);
}

////////////////////////////////////////////////////////////
/// Root table containing complete save game data
////////////////////////////////////////////////////////////
struct SaveData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SaveDataBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct SaveDataBuilder {
  typedef SaveData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit SaveDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SaveData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SaveData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SaveData> CreateSaveData(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  SaveDataBuilder builder_(_fbb);
  return builder_.Finish();
}

inline const steamrot::SaveData *GetSaveData(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::SaveData>(buf);
}

inline const steamrot::SaveData *GetSizePrefixedSaveData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::SaveData>(buf);
}

inline bool VerifySaveDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::SaveData>(nullptr);
}

inline bool VerifySizePrefixedSaveDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::SaveData>(nullptr);
}

inline void FinishSaveDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::SaveData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSaveDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::SaveData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_SAVEDATA_STEAMROT_H_
