// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCENEDATA_STEAMROT_H_
#define FLATBUFFERS_GENERATED_SCENEDATA_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "assets_generated.h"
#include "entities_generated.h"
#include "logic_data_generated.h"
#include "resource_data_generated.h"
#include "scene_types_generated.h"

namespace steamrot {

struct SceneDataData;
struct SceneDataDataBuilder;

struct SceneDataData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneDataDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_COLLECTION = 4,
    VT_ASSETS = 6,
    VT_SCENE_RESOURCES = 8,
    VT_SCENE_ID = 10,
    VT_SCENE_TYPE = 12,
    VT_LOGIC_COLLECTION_DATA = 14
  };
  const steamrot::EntityCollection *entity_collection() const {
    return GetPointer<const steamrot::EntityCollection *>(VT_ENTITY_COLLECTION);
  }
  const steamrot::AssetCollection *assets() const {
    return GetPointer<const steamrot::AssetCollection *>(VT_ASSETS);
  }
  const steamrot::SceneResourcesData *scene_resources() const {
    return GetPointer<const steamrot::SceneResourcesData *>(VT_SCENE_RESOURCES);
  }
  const ::flatbuffers::String *scene_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SCENE_ID);
  }
  steamrot::SceneType scene_type() const {
    return static_cast<steamrot::SceneType>(GetField<int8_t>(VT_SCENE_TYPE, 0));
  }
  const steamrot::LogicCollectionData *logic_collection_data() const {
    return GetPointer<const steamrot::LogicCollectionData *>(VT_LOGIC_COLLECTION_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTITY_COLLECTION) &&
           verifier.VerifyTable(entity_collection()) &&
           VerifyOffset(verifier, VT_ASSETS) &&
           verifier.VerifyTable(assets()) &&
           VerifyOffset(verifier, VT_SCENE_RESOURCES) &&
           verifier.VerifyTable(scene_resources()) &&
           VerifyOffset(verifier, VT_SCENE_ID) &&
           verifier.VerifyString(scene_id()) &&
           VerifyField<int8_t>(verifier, VT_SCENE_TYPE, 1) &&
           VerifyOffset(verifier, VT_LOGIC_COLLECTION_DATA) &&
           verifier.VerifyTable(logic_collection_data()) &&
           verifier.EndTable();
  }
};

struct SceneDataDataBuilder {
  typedef SceneDataData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_collection(::flatbuffers::Offset<steamrot::EntityCollection> entity_collection) {
    fbb_.AddOffset(SceneDataData::VT_ENTITY_COLLECTION, entity_collection);
  }
  void add_assets(::flatbuffers::Offset<steamrot::AssetCollection> assets) {
    fbb_.AddOffset(SceneDataData::VT_ASSETS, assets);
  }
  void add_scene_resources(::flatbuffers::Offset<steamrot::SceneResourcesData> scene_resources) {
    fbb_.AddOffset(SceneDataData::VT_SCENE_RESOURCES, scene_resources);
  }
  void add_scene_id(::flatbuffers::Offset<::flatbuffers::String> scene_id) {
    fbb_.AddOffset(SceneDataData::VT_SCENE_ID, scene_id);
  }
  void add_scene_type(steamrot::SceneType scene_type) {
    fbb_.AddElement<int8_t>(SceneDataData::VT_SCENE_TYPE, static_cast<int8_t>(scene_type), 0);
  }
  void add_logic_collection_data(::flatbuffers::Offset<steamrot::LogicCollectionData> logic_collection_data) {
    fbb_.AddOffset(SceneDataData::VT_LOGIC_COLLECTION_DATA, logic_collection_data);
  }
  explicit SceneDataDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneDataData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneDataData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneDataData> CreateSceneDataData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::EntityCollection> entity_collection = 0,
    ::flatbuffers::Offset<steamrot::AssetCollection> assets = 0,
    ::flatbuffers::Offset<steamrot::SceneResourcesData> scene_resources = 0,
    ::flatbuffers::Offset<::flatbuffers::String> scene_id = 0,
    steamrot::SceneType scene_type = steamrot::SceneType_UNKNOWN,
    ::flatbuffers::Offset<steamrot::LogicCollectionData> logic_collection_data = 0) {
  SceneDataDataBuilder builder_(_fbb);
  builder_.add_logic_collection_data(logic_collection_data);
  builder_.add_scene_id(scene_id);
  builder_.add_scene_resources(scene_resources);
  builder_.add_assets(assets);
  builder_.add_entity_collection(entity_collection);
  builder_.add_scene_type(scene_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SceneDataData> CreateSceneDataDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::EntityCollection> entity_collection = 0,
    ::flatbuffers::Offset<steamrot::AssetCollection> assets = 0,
    ::flatbuffers::Offset<steamrot::SceneResourcesData> scene_resources = 0,
    const char *scene_id = nullptr,
    steamrot::SceneType scene_type = steamrot::SceneType_UNKNOWN,
    ::flatbuffers::Offset<steamrot::LogicCollectionData> logic_collection_data = 0) {
  auto scene_id__ = scene_id ? _fbb.CreateString(scene_id) : 0;
  return steamrot::CreateSceneDataData(
      _fbb,
      entity_collection,
      assets,
      scene_resources,
      scene_id__,
      scene_type,
      logic_collection_data);
}

inline const steamrot::SceneDataData *GetSceneDataData(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::SceneDataData>(buf);
}

inline const steamrot::SceneDataData *GetSizePrefixedSceneDataData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::SceneDataData>(buf);
}

inline bool VerifySceneDataDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::SceneDataData>(nullptr);
}

inline bool VerifySizePrefixedSceneDataDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::SceneDataData>(nullptr);
}

inline void FinishSceneDataDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::SceneDataData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSceneDataDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::SceneDataData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_SCENEDATA_STEAMROT_H_
