// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCENEMANAGERSTATE_STEAMROT_H_
#define FLATBUFFERS_GENERATED_SCENEMANAGERSTATE_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "subscriber_data_generated.h"

namespace steamrot {

struct SceneManagerStateFbs;
struct SceneManagerStateFbsBuilder;

struct SceneManagerStateFbs FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneManagerStateFbsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBSCRIPTIONS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>> *subscriptions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>> *>(VT_SUBSCRIPTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SUBSCRIPTIONS) &&
           verifier.VerifyVector(subscriptions()) &&
           verifier.VerifyVectorOfTables(subscriptions()) &&
           verifier.EndTable();
  }
};

struct SceneManagerStateFbsBuilder {
  typedef SceneManagerStateFbs Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_subscriptions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>>> subscriptions) {
    fbb_.AddOffset(SceneManagerStateFbs::VT_SUBSCRIPTIONS, subscriptions);
  }
  explicit SceneManagerStateFbsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneManagerStateFbs> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneManagerStateFbs>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneManagerStateFbs> CreateSceneManagerStateFbs(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>>> subscriptions = 0) {
  SceneManagerStateFbsBuilder builder_(_fbb);
  builder_.add_subscriptions(subscriptions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SceneManagerStateFbs> CreateSceneManagerStateFbsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<steamrot::SubscriberData>> *subscriptions = nullptr) {
  auto subscriptions__ = subscriptions ? _fbb.CreateVector<::flatbuffers::Offset<steamrot::SubscriberData>>(*subscriptions) : 0;
  return steamrot::CreateSceneManagerStateFbs(
      _fbb,
      subscriptions__);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_SCENEMANAGERSTATE_STEAMROT_H_
