// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCENEDATA_STEAMROT_H_
#define FLATBUFFERS_GENERATED_SCENEDATA_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "assets_generated.h"
#include "entities_generated.h"
#include "resource_data_generated.h"
#include "scene_types_generated.h"

namespace steamrot {

struct SceneData;
struct SceneDataBuilder;

struct SceneData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_COLLECTION = 4,
    VT_ASSETS = 6,
    VT_SCENE_RESOURCES = 8,
    VT_SCENE_ID = 10,
    VT_SCENE_TYPE = 12
  };
  const steamrot::EntityCollection *entity_collection() const {
    return GetPointer<const steamrot::EntityCollection *>(VT_ENTITY_COLLECTION);
  }
  const steamrot::AssetCollection *assets() const {
    return GetPointer<const steamrot::AssetCollection *>(VT_ASSETS);
  }
  const steamrot::SceneResourcesData *scene_resources() const {
    return GetPointer<const steamrot::SceneResourcesData *>(VT_SCENE_RESOURCES);
  }
  const ::flatbuffers::String *scene_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SCENE_ID);
  }
  steamrot::SceneType scene_type() const {
    return static_cast<steamrot::SceneType>(GetField<int8_t>(VT_SCENE_TYPE, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTITY_COLLECTION) &&
           verifier.VerifyTable(entity_collection()) &&
           VerifyOffset(verifier, VT_ASSETS) &&
           verifier.VerifyTable(assets()) &&
           VerifyOffset(verifier, VT_SCENE_RESOURCES) &&
           verifier.VerifyTable(scene_resources()) &&
           VerifyOffset(verifier, VT_SCENE_ID) &&
           verifier.VerifyString(scene_id()) &&
           VerifyField<int8_t>(verifier, VT_SCENE_TYPE, 1) &&
           verifier.EndTable();
  }
};

struct SceneDataBuilder {
  typedef SceneData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_collection(::flatbuffers::Offset<steamrot::EntityCollection> entity_collection) {
    fbb_.AddOffset(SceneData::VT_ENTITY_COLLECTION, entity_collection);
  }
  void add_assets(::flatbuffers::Offset<steamrot::AssetCollection> assets) {
    fbb_.AddOffset(SceneData::VT_ASSETS, assets);
  }
  void add_scene_resources(::flatbuffers::Offset<steamrot::SceneResourcesData> scene_resources) {
    fbb_.AddOffset(SceneData::VT_SCENE_RESOURCES, scene_resources);
  }
  void add_scene_id(::flatbuffers::Offset<::flatbuffers::String> scene_id) {
    fbb_.AddOffset(SceneData::VT_SCENE_ID, scene_id);
  }
  void add_scene_type(steamrot::SceneType scene_type) {
    fbb_.AddElement<int8_t>(SceneData::VT_SCENE_TYPE, static_cast<int8_t>(scene_type), 0);
  }
  explicit SceneDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneData> CreateSceneData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::EntityCollection> entity_collection = 0,
    ::flatbuffers::Offset<steamrot::AssetCollection> assets = 0,
    ::flatbuffers::Offset<steamrot::SceneResourcesData> scene_resources = 0,
    ::flatbuffers::Offset<::flatbuffers::String> scene_id = 0,
    steamrot::SceneType scene_type = steamrot::SceneType_UNKNOWN) {
  SceneDataBuilder builder_(_fbb);
  builder_.add_scene_id(scene_id);
  builder_.add_scene_resources(scene_resources);
  builder_.add_assets(assets);
  builder_.add_entity_collection(entity_collection);
  builder_.add_scene_type(scene_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SceneData> CreateSceneDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::EntityCollection> entity_collection = 0,
    ::flatbuffers::Offset<steamrot::AssetCollection> assets = 0,
    ::flatbuffers::Offset<steamrot::SceneResourcesData> scene_resources = 0,
    const char *scene_id = nullptr,
    steamrot::SceneType scene_type = steamrot::SceneType_UNKNOWN) {
  auto scene_id__ = scene_id ? _fbb.CreateString(scene_id) : 0;
  return steamrot::CreateSceneData(
      _fbb,
      entity_collection,
      assets,
      scene_resources,
      scene_id__,
      scene_type);
}

inline const steamrot::SceneData *GetSceneData(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::SceneData>(buf);
}

inline const steamrot::SceneData *GetSizePrefixedSceneData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::SceneData>(buf);
}

inline bool VerifySceneDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::SceneData>(nullptr);
}

inline bool VerifySizePrefixedSceneDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::SceneData>(nullptr);
}

inline void FinishSceneDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::SceneData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSceneDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::SceneData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_SCENEDATA_STEAMROT_H_
