// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCENEMANAGER_STEAMROT_H_
#define FLATBUFFERS_GENERATED_SCENEMANAGER_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "subscriber_config_generated.h"

namespace steamrot {

struct SceneManagerData;
struct SceneManagerDataBuilder;

struct SceneManagerData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneManagerDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SUBSCRIPTIONS = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>> *subscriptions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>> *>(VT_SUBSCRIPTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SUBSCRIPTIONS) &&
           verifier.VerifyVector(subscriptions()) &&
           verifier.VerifyVectorOfTables(subscriptions()) &&
           verifier.EndTable();
  }
};

struct SceneManagerDataBuilder {
  typedef SceneManagerData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_subscriptions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>>> subscriptions) {
    fbb_.AddOffset(SceneManagerData::VT_SUBSCRIPTIONS, subscriptions);
  }
  explicit SceneManagerDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SceneManagerData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SceneManagerData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SceneManagerData> CreateSceneManagerData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SubscriberData>>> subscriptions = 0) {
  SceneManagerDataBuilder builder_(_fbb);
  builder_.add_subscriptions(subscriptions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SceneManagerData> CreateSceneManagerDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<steamrot::SubscriberData>> *subscriptions = nullptr) {
  auto subscriptions__ = subscriptions ? _fbb.CreateVector<::flatbuffers::Offset<steamrot::SubscriberData>>(*subscriptions) : 0;
  return steamrot::CreateSceneManagerData(
      _fbb,
      subscriptions__);
}

inline const steamrot::SceneManagerData *GetSceneManagerData(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::SceneManagerData>(buf);
}

inline const steamrot::SceneManagerData *GetSizePrefixedSceneManagerData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::SceneManagerData>(buf);
}

inline bool VerifySceneManagerDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::SceneManagerData>(nullptr);
}

inline bool VerifySizePrefixedSceneManagerDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::SceneManagerData>(nullptr);
}

inline void FinishSceneManagerDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::SceneManagerData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSceneManagerDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::SceneManagerData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_SCENEMANAGER_STEAMROT_H_
