// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIMULATION_STEAMROT_H_
#define FLATBUFFERS_GENERATED_SIMULATION_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace steamrot {

struct SimulationStep;
struct SimulationStepBuilder;

struct SimulationData;
struct SimulationDataBuilder;

////////////////////////////////////////////////////////////
/// @brief Types of simulation systems matching Scene logic organization
////////////////////////////////////////////////////////////
enum SimulationType : int8_t {
  SimulationType_Action = 0,
  SimulationType_Movement = 1,
  SimulationType_Render = 2,
  SimulationType_Collision = 3,
  SimulationType_MIN = SimulationType_Action,
  SimulationType_MAX = SimulationType_Collision
};

inline const SimulationType (&EnumValuesSimulationType())[4] {
  static const SimulationType values[] = {
    SimulationType_Action,
    SimulationType_Movement,
    SimulationType_Render,
    SimulationType_Collision
  };
  return values;
}

inline const char * const *EnumNamesSimulationType() {
  static const char * const names[5] = {
    "Action",
    "Movement",
    "Render",
    "Collision",
    nullptr
  };
  return names;
}

inline const char *EnumNameSimulationType(SimulationType e) {
  if (::flatbuffers::IsOutRange(e, SimulationType_Action, SimulationType_Collision)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSimulationType()[index];
}

////////////////////////////////////////////////////////////
/// @brief Types of individual functions that can be called during simulation
///
/// This enum allows test data to specify which specific free functions
/// to call during simulation execution.
////////////////////////////////////////////////////////////
enum FunctionType : int8_t {
  FunctionType_None = 0,
  FunctionType_ProcessUIActionsAndEvents = 1,
  FunctionType_ProcessNestedUIActionsAndEvents = 2,
  FunctionType_ProcessButtonElementActions = 3,
  FunctionType_ProcessDropDownListElementActions = 4,
  FunctionType_CheckMouseOverNestedUIElement = 5,
  FunctionType_UpdateCUserInterfaceVisibilityFromCUIState = 6,
  FunctionType_MIN = FunctionType_None,
  FunctionType_MAX = FunctionType_UpdateCUserInterfaceVisibilityFromCUIState
};

inline const FunctionType (&EnumValuesFunctionType())[7] {
  static const FunctionType values[] = {
    FunctionType_None,
    FunctionType_ProcessUIActionsAndEvents,
    FunctionType_ProcessNestedUIActionsAndEvents,
    FunctionType_ProcessButtonElementActions,
    FunctionType_ProcessDropDownListElementActions,
    FunctionType_CheckMouseOverNestedUIElement,
    FunctionType_UpdateCUserInterfaceVisibilityFromCUIState
  };
  return values;
}

inline const char * const *EnumNamesFunctionType() {
  static const char * const names[8] = {
    "None",
    "ProcessUIActionsAndEvents",
    "ProcessNestedUIActionsAndEvents",
    "ProcessButtonElementActions",
    "ProcessDropDownListElementActions",
    "CheckMouseOverNestedUIElement",
    "UpdateCUserInterfaceVisibilityFromCUIState",
    nullptr
  };
  return names;
}

inline const char *EnumNameFunctionType(FunctionType e) {
  if (::flatbuffers::IsOutRange(e, FunctionType_None, FunctionType_UpdateCUserInterfaceVisibilityFromCUIState)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFunctionType()[index];
}

////////////////////////////////////////////////////////////
/// @brief Execution mode for a simulation step
///
/// Determines whether to execute individual functions or entire Logic classes
////////////////////////////////////////////////////////////
enum ExecutionMode : int8_t {
  /// Execute individual free function specified by function_type
  ExecutionMode_Function = 0,
  /// Execute entire Logic class specified by logic_type
  ExecutionMode_LogicClass = 1,
  ExecutionMode_MIN = ExecutionMode_Function,
  ExecutionMode_MAX = ExecutionMode_LogicClass
};

inline const ExecutionMode (&EnumValuesExecutionMode())[2] {
  static const ExecutionMode values[] = {
    ExecutionMode_Function,
    ExecutionMode_LogicClass
  };
  return values;
}

inline const char * const *EnumNamesExecutionMode() {
  static const char * const names[3] = {
    "Function",
    "LogicClass",
    nullptr
  };
  return names;
}

inline const char *EnumNameExecutionMode(ExecutionMode e) {
  if (::flatbuffers::IsOutRange(e, ExecutionMode_Function, ExecutionMode_LogicClass)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesExecutionMode()[index];
}

////////////////////////////////////////////////////////////
/// @brief Logic class types that can be executed
///
/// Matches the Logic class hierarchy in the codebase
////////////////////////////////////////////////////////////
enum LogicClassType : int8_t {
  LogicClassType_None = 0,
  LogicClassType_UIActionLogic = 1,
  LogicClassType_UICollisionLogic = 2,
  LogicClassType_UIRenderLogic = 3,
  LogicClassType_UIStateLogic = 4,
  LogicClassType_CraftingRenderLogic = 5,
  LogicClassType_MIN = LogicClassType_None,
  LogicClassType_MAX = LogicClassType_CraftingRenderLogic
};

inline const LogicClassType (&EnumValuesLogicClassType())[6] {
  static const LogicClassType values[] = {
    LogicClassType_None,
    LogicClassType_UIActionLogic,
    LogicClassType_UICollisionLogic,
    LogicClassType_UIRenderLogic,
    LogicClassType_UIStateLogic,
    LogicClassType_CraftingRenderLogic
  };
  return values;
}

inline const char * const *EnumNamesLogicClassType() {
  static const char * const names[7] = {
    "None",
    "UIActionLogic",
    "UICollisionLogic",
    "UIRenderLogic",
    "UIStateLogic",
    "CraftingRenderLogic",
    nullptr
  };
  return names;
}

inline const char *EnumNameLogicClassType(LogicClassType e) {
  if (::flatbuffers::IsOutRange(e, LogicClassType_None, LogicClassType_CraftingRenderLogic)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLogicClassType()[index];
}

////////////////////////////////////////////////////////////
/// @brief A single step in a simulation sequence
///
/// Each step specifies what to execute (function or Logic class)
/// and which system category it belongs to.
////////////////////////////////////////////////////////////
struct SimulationStep FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SimulationStepBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIMULATION_TYPE = 4,
    VT_EXECUTION_MODE = 6,
    VT_FUNCTION_TYPE = 8,
    VT_LOGIC_CLASS_TYPE = 10,
    VT_DESCRIPTION = 12
  };
  /// @brief Which system this step belongs to (Action, Movement, Render, Collision)
  steamrot::SimulationType simulation_type() const {
    return static_cast<steamrot::SimulationType>(GetField<int8_t>(VT_SIMULATION_TYPE, 0));
  }
  /// @brief Whether to execute a function or a Logic class
  steamrot::ExecutionMode execution_mode() const {
    return static_cast<steamrot::ExecutionMode>(GetField<int8_t>(VT_EXECUTION_MODE, 0));
  }
  /// @brief Which specific function to call (if execution_mode is Function)
  steamrot::FunctionType function_type() const {
    return static_cast<steamrot::FunctionType>(GetField<int8_t>(VT_FUNCTION_TYPE, 0));
  }
  /// @brief Which Logic class to execute (if execution_mode is LogicClass)
  steamrot::LogicClassType logic_class_type() const {
    return static_cast<steamrot::LogicClassType>(GetField<int8_t>(VT_LOGIC_CLASS_TYPE, 0));
  }
  /// @brief Optional description of what this step does
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_SIMULATION_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_EXECUTION_MODE, 1) &&
           VerifyField<int8_t>(verifier, VT_FUNCTION_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_LOGIC_CLASS_TYPE, 1) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           verifier.EndTable();
  }
};

struct SimulationStepBuilder {
  typedef SimulationStep Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_simulation_type(steamrot::SimulationType simulation_type) {
    fbb_.AddElement<int8_t>(SimulationStep::VT_SIMULATION_TYPE, static_cast<int8_t>(simulation_type), 0);
  }
  void add_execution_mode(steamrot::ExecutionMode execution_mode) {
    fbb_.AddElement<int8_t>(SimulationStep::VT_EXECUTION_MODE, static_cast<int8_t>(execution_mode), 0);
  }
  void add_function_type(steamrot::FunctionType function_type) {
    fbb_.AddElement<int8_t>(SimulationStep::VT_FUNCTION_TYPE, static_cast<int8_t>(function_type), 0);
  }
  void add_logic_class_type(steamrot::LogicClassType logic_class_type) {
    fbb_.AddElement<int8_t>(SimulationStep::VT_LOGIC_CLASS_TYPE, static_cast<int8_t>(logic_class_type), 0);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(SimulationStep::VT_DESCRIPTION, description);
  }
  explicit SimulationStepBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SimulationStep> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SimulationStep>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SimulationStep> CreateSimulationStep(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    steamrot::SimulationType simulation_type = steamrot::SimulationType_Action,
    steamrot::ExecutionMode execution_mode = steamrot::ExecutionMode_Function,
    steamrot::FunctionType function_type = steamrot::FunctionType_None,
    steamrot::LogicClassType logic_class_type = steamrot::LogicClassType_None,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0) {
  SimulationStepBuilder builder_(_fbb);
  builder_.add_description(description);
  builder_.add_logic_class_type(logic_class_type);
  builder_.add_function_type(function_type);
  builder_.add_execution_mode(execution_mode);
  builder_.add_simulation_type(simulation_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SimulationStep> CreateSimulationStepDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    steamrot::SimulationType simulation_type = steamrot::SimulationType_Action,
    steamrot::ExecutionMode execution_mode = steamrot::ExecutionMode_Function,
    steamrot::FunctionType function_type = steamrot::FunctionType_None,
    steamrot::LogicClassType logic_class_type = steamrot::LogicClassType_None,
    const char *description = nullptr) {
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return steamrot::CreateSimulationStep(
      _fbb,
      simulation_type,
      execution_mode,
      function_type,
      logic_class_type,
      description__);
}

////////////////////////////////////////////////////////////
/// @brief Complete simulation configuration
///
/// Defines a sequence of steps to execute during testing.
/// Steps are executed in the order they appear in the array.
////////////////////////////////////////////////////////////
struct SimulationData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SimulationDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STEPS = 4,
    VT_DESCRIPTION = 6,
    VT_NUM_TICKS = 8
  };
  /// @brief Ordered sequence of simulation steps to execute
  const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SimulationStep>> *steps() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SimulationStep>> *>(VT_STEPS);
  }
  /// @brief Optional description of the overall simulation
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  /// @brief DEPRECATED: This field is NOT used for tick determination.
  /// Use TestDataConfig.num_ticks instead to control tick count.
  /// This field is kept for backward compatibility but has no effect.
  uint32_t num_ticks() const {
    return GetField<uint32_t>(VT_NUM_TICKS, 1);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STEPS) &&
           verifier.VerifyVector(steps()) &&
           verifier.VerifyVectorOfTables(steps()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyField<uint32_t>(verifier, VT_NUM_TICKS, 4) &&
           verifier.EndTable();
  }
};

struct SimulationDataBuilder {
  typedef SimulationData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_steps(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SimulationStep>>> steps) {
    fbb_.AddOffset(SimulationData::VT_STEPS, steps);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(SimulationData::VT_DESCRIPTION, description);
  }
  void add_num_ticks(uint32_t num_ticks) {
    fbb_.AddElement<uint32_t>(SimulationData::VT_NUM_TICKS, num_ticks, 1);
  }
  explicit SimulationDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SimulationData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SimulationData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SimulationData> CreateSimulationData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::SimulationStep>>> steps = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    uint32_t num_ticks = 1) {
  SimulationDataBuilder builder_(_fbb);
  builder_.add_num_ticks(num_ticks);
  builder_.add_description(description);
  builder_.add_steps(steps);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SimulationData> CreateSimulationDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<steamrot::SimulationStep>> *steps = nullptr,
    const char *description = nullptr,
    uint32_t num_ticks = 1) {
  auto steps__ = steps ? _fbb.CreateVector<::flatbuffers::Offset<steamrot::SimulationStep>>(*steps) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return steamrot::CreateSimulationData(
      _fbb,
      steps__,
      description__,
      num_ticks);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_SIMULATION_STEAMROT_H_
