// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SUBSCRIBERCONFIG_STEAMROT_H_
#define FLATBUFFERS_GENERATED_SUBSCRIBERCONFIG_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "events_generated.h"

namespace steamrot {

struct SubscriberData;
struct SubscriberDataBuilder;

struct SubscriberData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SubscriberDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_EVENT_TYPE_DATA = 4
  };
  steamrot::EventType event_type_data() const {
    return static_cast<steamrot::EventType>(GetField<uint64_t>(VT_EVENT_TYPE_DATA, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_EVENT_TYPE_DATA, 8) &&
           verifier.EndTable();
  }
};

struct SubscriberDataBuilder {
  typedef SubscriberData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_event_type_data(steamrot::EventType event_type_data) {
    fbb_.AddElement<uint64_t>(SubscriberData::VT_EVENT_TYPE_DATA, static_cast<uint64_t>(event_type_data), 0);
  }
  explicit SubscriberDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SubscriberData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SubscriberData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SubscriberData> CreateSubscriberData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    steamrot::EventType event_type_data = static_cast<steamrot::EventType>(0)) {
  SubscriberDataBuilder builder_(_fbb);
  builder_.add_event_type_data(event_type_data);
  return builder_.Finish();
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_SUBSCRIBERCONFIG_STEAMROT_H_
