// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TESTDATA_STEAMROT_H_
#define FLATBUFFERS_GENERATED_TESTDATA_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "engine_data_generated.h"
#include "entities_generated.h"
#include "event_bus_data_generated.h"
#include "event_test_data_generated.h"
#include "input_test_data_generated.h"
#include "resource_data_generated.h"
#include "simulation_generated.h"

namespace steamrot {

struct TickSnapshot;
struct TickSnapshotBuilder;

struct TestMetadata;
struct TestMetadataBuilder;

struct TestDataConfig;
struct TestDataConfigBuilder;

////////////////////////////////////////////////////////////
/// @brief Snapshot of expected data structure state at a specific tick
///
/// Represents a checkpoint during test execution where the
/// actual data structure state should match the expected state defined
/// in the data_collection field.
///
/// Note: Tick numbering is 1-based to mimic the game loop.
/// The setup phase occurs before tick 1. Valid tick values start at 1.
////////////////////////////////////////////////////////////
struct TickSnapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TickSnapshotBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICK = 4,
    VT_ENGINE_STATE = 6,
    VT_DESCRIPTION = 8,
    VT_INPUT_SEQUENCE = 10,
    VT_EVENT_SEQUENCE = 12
  };
  /// @brief Tick number when this snapshot should be compared (1-based)
  /// The comparison happens AFTER simulation steps execute for this tick,
  /// but BEFORE the event bus is ticked.
  /// Valid values: 1, 2, 3, ... (matching game loop tick numbers)
  uint32_t tick() const {
    return GetField<uint32_t>(VT_TICK, 0);
  }
  const steamrot::EngineData *engine_state() const {
    return GetPointer<const steamrot::EngineData *>(VT_ENGINE_STATE);
  }
  /// @brief Optional human-readable description of this checkpoint
  /// Used in failure messages to identify which snapshot failed.
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  /// @brief Inputs to inject at specific tick
  const steamrot::InputSequence *input_sequence() const {
    return GetPointer<const steamrot::InputSequence *>(VT_INPUT_SEQUENCE);
  }
  /// @brief Events to inject at specific tick
  const steamrot::EventSequence *event_sequence() const {
    return GetPointer<const steamrot::EventSequence *>(VT_EVENT_SEQUENCE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TICK, 4) &&
           VerifyOffset(verifier, VT_ENGINE_STATE) &&
           verifier.VerifyTable(engine_state()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_INPUT_SEQUENCE) &&
           verifier.VerifyTable(input_sequence()) &&
           VerifyOffset(verifier, VT_EVENT_SEQUENCE) &&
           verifier.VerifyTable(event_sequence()) &&
           verifier.EndTable();
  }
};

struct TickSnapshotBuilder {
  typedef TickSnapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tick(uint32_t tick) {
    fbb_.AddElement<uint32_t>(TickSnapshot::VT_TICK, tick, 0);
  }
  void add_engine_state(::flatbuffers::Offset<steamrot::EngineData> engine_state) {
    fbb_.AddOffset(TickSnapshot::VT_ENGINE_STATE, engine_state);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(TickSnapshot::VT_DESCRIPTION, description);
  }
  void add_input_sequence(::flatbuffers::Offset<steamrot::InputSequence> input_sequence) {
    fbb_.AddOffset(TickSnapshot::VT_INPUT_SEQUENCE, input_sequence);
  }
  void add_event_sequence(::flatbuffers::Offset<steamrot::EventSequence> event_sequence) {
    fbb_.AddOffset(TickSnapshot::VT_EVENT_SEQUENCE, event_sequence);
  }
  explicit TickSnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TickSnapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TickSnapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TickSnapshot> CreateTickSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick = 0,
    ::flatbuffers::Offset<steamrot::EngineData> engine_state = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<steamrot::InputSequence> input_sequence = 0,
    ::flatbuffers::Offset<steamrot::EventSequence> event_sequence = 0) {
  TickSnapshotBuilder builder_(_fbb);
  builder_.add_event_sequence(event_sequence);
  builder_.add_input_sequence(input_sequence);
  builder_.add_description(description);
  builder_.add_engine_state(engine_state);
  builder_.add_tick(tick);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TickSnapshot> CreateTickSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick = 0,
    ::flatbuffers::Offset<steamrot::EngineData> engine_state = 0,
    const char *description = nullptr,
    ::flatbuffers::Offset<steamrot::InputSequence> input_sequence = 0,
    ::flatbuffers::Offset<steamrot::EventSequence> event_sequence = 0) {
  auto description__ = description ? _fbb.CreateString(description) : 0;
  return steamrot::CreateTickSnapshot(
      _fbb,
      tick,
      engine_state,
      description__,
      input_sequence,
      event_sequence);
}

////////////////////////////////////////////////////////////
/// @brief Test metadata for data-driven testing
///
/// This table contains metadata about a test case that can
/// be extended in the future with additional fields.
////////////////////////////////////////////////////////////
struct TestMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEST_NAME = 4,
    VT_DESCRIPTION = 6,
    VT_TAGS = 8,
    VT_EXPECTED_TO_PASS = 10,
    VT_AUTHOR = 12,
    VT_VERSION = 14
  };
  /// @brief Human-readable name for the test case
  const ::flatbuffers::String *test_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEST_NAME);
  }
  /// @brief Optional description of what the test validates
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  /// @brief Tags for categorizing tests (e.g., "unit", "integration")
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *tags() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_TAGS);
  }
  /// @brief Expected test outcome (true = should pass, false = should fail)
  bool expected_to_pass() const {
    return GetField<uint8_t>(VT_EXPECTED_TO_PASS, 1) != 0;
  }
  /// @brief Optional author or creator of the test case
  const ::flatbuffers::String *author() const {
    return GetPointer<const ::flatbuffers::String *>(VT_AUTHOR);
  }
  /// @brief Version identifier for the test data format
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TEST_NAME) &&
           verifier.VerifyString(test_name()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_TAGS) &&
           verifier.VerifyVector(tags()) &&
           verifier.VerifyVectorOfStrings(tags()) &&
           VerifyField<uint8_t>(verifier, VT_EXPECTED_TO_PASS, 1) &&
           VerifyOffset(verifier, VT_AUTHOR) &&
           verifier.VerifyString(author()) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           verifier.EndTable();
  }
};

struct TestMetadataBuilder {
  typedef TestMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_test_name(::flatbuffers::Offset<::flatbuffers::String> test_name) {
    fbb_.AddOffset(TestMetadata::VT_TEST_NAME, test_name);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(TestMetadata::VT_DESCRIPTION, description);
  }
  void add_tags(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> tags) {
    fbb_.AddOffset(TestMetadata::VT_TAGS, tags);
  }
  void add_expected_to_pass(bool expected_to_pass) {
    fbb_.AddElement<uint8_t>(TestMetadata::VT_EXPECTED_TO_PASS, static_cast<uint8_t>(expected_to_pass), 1);
  }
  void add_author(::flatbuffers::Offset<::flatbuffers::String> author) {
    fbb_.AddOffset(TestMetadata::VT_AUTHOR, author);
  }
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(TestMetadata::VT_VERSION, version, 1);
  }
  explicit TestMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TestMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TestMetadata>(end);
    fbb_.Required(o, TestMetadata::VT_TEST_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<TestMetadata> CreateTestMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> test_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> tags = 0,
    bool expected_to_pass = true,
    ::flatbuffers::Offset<::flatbuffers::String> author = 0,
    uint32_t version = 1) {
  TestMetadataBuilder builder_(_fbb);
  builder_.add_version(version);
  builder_.add_author(author);
  builder_.add_tags(tags);
  builder_.add_description(description);
  builder_.add_test_name(test_name);
  builder_.add_expected_to_pass(expected_to_pass);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TestMetadata> CreateTestMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *test_name = nullptr,
    const char *description = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *tags = nullptr,
    bool expected_to_pass = true,
    const char *author = nullptr,
    uint32_t version = 1) {
  auto test_name__ = test_name ? _fbb.CreateString(test_name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto tags__ = tags ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*tags) : 0;
  auto author__ = author ? _fbb.CreateString(author) : 0;
  return steamrot::CreateTestMetadata(
      _fbb,
      test_name__,
      description__,
      tags__,
      expected_to_pass,
      author__,
      version);
}

////////////////////////////////////////////////////////////
/// @brief Root table for test data configuration
///
/// This is the main container for test data. It's designed
/// to be extensible - new data types can be added as optional
/// fields without breaking existing tests.
////////////////////////////////////////////////////////////
struct TestDataConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestDataConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_METADATA = 4,
    VT_STARTING_ENGINE_STATE = 6,
    VT_SIMULATION_DATA = 8,
    VT_NUM_TICKS = 10,
    VT_TICK_SNAPSHOTS = 12
  };
  /// @brief Metadata about this test case
  const steamrot::TestMetadata *metadata() const {
    return GetPointer<const steamrot::TestMetadata *>(VT_METADATA);
  }
  const steamrot::EngineData *starting_engine_state() const {
    return GetPointer<const steamrot::EngineData *>(VT_STARTING_ENGINE_STATE);
  }
  /// @brief Simulation data for executing logic steps during tests
  const steamrot::SimulationData *simulation_data() const {
    return GetPointer<const steamrot::SimulationData *>(VT_SIMULATION_DATA);
  }
  /// @brief Number of ticks to run the test for (default: 1)
  /// This is the ONLY field consulted to determine tick count. The test will execute for exactly
  /// this many ticks, processing inputs, events, and simulation steps scheduled for each tick.
  /// If not specified (value is 0), defaults to 1 tick.
  /// Note: input_sequence, event_sequence, and simulation_data.num_ticks are NOT consulted
  /// for tick determination. Only this TestDataConfig level field is used.
  uint32_t num_ticks() const {
    return GetField<uint32_t>(VT_NUM_TICKS, 0);
  }
  /// @brief Intermediate entity state snapshots for tick-by-tick validation
  /// Optional field. If present, the test harness will compare actual entity
  /// state with expected state at each specified tick.
  /// Snapshots are compared AFTER simulation steps but BEFORE event bus tick.
  const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::TickSnapshot>> *tick_snapshots() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<steamrot::TickSnapshot>> *>(VT_TICK_SNAPSHOTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_METADATA) &&
           verifier.VerifyTable(metadata()) &&
           VerifyOffset(verifier, VT_STARTING_ENGINE_STATE) &&
           verifier.VerifyTable(starting_engine_state()) &&
           VerifyOffset(verifier, VT_SIMULATION_DATA) &&
           verifier.VerifyTable(simulation_data()) &&
           VerifyField<uint32_t>(verifier, VT_NUM_TICKS, 4) &&
           VerifyOffset(verifier, VT_TICK_SNAPSHOTS) &&
           verifier.VerifyVector(tick_snapshots()) &&
           verifier.VerifyVectorOfTables(tick_snapshots()) &&
           verifier.EndTable();
  }
};

struct TestDataConfigBuilder {
  typedef TestDataConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_metadata(::flatbuffers::Offset<steamrot::TestMetadata> metadata) {
    fbb_.AddOffset(TestDataConfig::VT_METADATA, metadata);
  }
  void add_starting_engine_state(::flatbuffers::Offset<steamrot::EngineData> starting_engine_state) {
    fbb_.AddOffset(TestDataConfig::VT_STARTING_ENGINE_STATE, starting_engine_state);
  }
  void add_simulation_data(::flatbuffers::Offset<steamrot::SimulationData> simulation_data) {
    fbb_.AddOffset(TestDataConfig::VT_SIMULATION_DATA, simulation_data);
  }
  void add_num_ticks(uint32_t num_ticks) {
    fbb_.AddElement<uint32_t>(TestDataConfig::VT_NUM_TICKS, num_ticks, 0);
  }
  void add_tick_snapshots(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::TickSnapshot>>> tick_snapshots) {
    fbb_.AddOffset(TestDataConfig::VT_TICK_SNAPSHOTS, tick_snapshots);
  }
  explicit TestDataConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TestDataConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TestDataConfig>(end);
    fbb_.Required(o, TestDataConfig::VT_METADATA);
    return o;
  }
};

inline ::flatbuffers::Offset<TestDataConfig> CreateTestDataConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::TestMetadata> metadata = 0,
    ::flatbuffers::Offset<steamrot::EngineData> starting_engine_state = 0,
    ::flatbuffers::Offset<steamrot::SimulationData> simulation_data = 0,
    uint32_t num_ticks = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<steamrot::TickSnapshot>>> tick_snapshots = 0) {
  TestDataConfigBuilder builder_(_fbb);
  builder_.add_tick_snapshots(tick_snapshots);
  builder_.add_num_ticks(num_ticks);
  builder_.add_simulation_data(simulation_data);
  builder_.add_starting_engine_state(starting_engine_state);
  builder_.add_metadata(metadata);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TestDataConfig> CreateTestDataConfigDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::TestMetadata> metadata = 0,
    ::flatbuffers::Offset<steamrot::EngineData> starting_engine_state = 0,
    ::flatbuffers::Offset<steamrot::SimulationData> simulation_data = 0,
    uint32_t num_ticks = 0,
    const std::vector<::flatbuffers::Offset<steamrot::TickSnapshot>> *tick_snapshots = nullptr) {
  auto tick_snapshots__ = tick_snapshots ? _fbb.CreateVector<::flatbuffers::Offset<steamrot::TickSnapshot>>(*tick_snapshots) : 0;
  return steamrot::CreateTestDataConfig(
      _fbb,
      metadata,
      starting_engine_state,
      simulation_data,
      num_ticks,
      tick_snapshots__);
}

inline const steamrot::TestDataConfig *GetTestDataConfig(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::TestDataConfig>(buf);
}

inline const steamrot::TestDataConfig *GetSizePrefixedTestDataConfig(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::TestDataConfig>(buf);
}

inline bool VerifyTestDataConfigBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::TestDataConfig>(nullptr);
}

inline bool VerifySizePrefixedTestDataConfigBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::TestDataConfig>(nullptr);
}

inline void FinishTestDataConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::TestDataConfig> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTestDataConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::TestDataConfig> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_TESTDATA_STEAMROT_H_
