// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TESTDATA_STEAMROT_H_
#define FLATBUFFERS_GENERATED_TESTDATA_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "entities_generated.h"
#include "resource_data_generated.h"

namespace steamrot {

struct TestMetadata;
struct TestMetadataBuilder;

struct TestDataConfig;
struct TestDataConfigBuilder;

////////////////////////////////////////////////////////////
/// @brief Test metadata for data-driven testing
///
/// This table contains metadata about a test case that can
/// be extended in the future with additional fields.
////////////////////////////////////////////////////////////
struct TestMetadata FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestMetadataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEST_NAME = 4,
    VT_DESCRIPTION = 6,
    VT_TAGS = 8,
    VT_EXPECTED_TO_PASS = 10,
    VT_AUTHOR = 12,
    VT_VERSION = 14
  };
  /// @brief Human-readable name for the test case
  const ::flatbuffers::String *test_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TEST_NAME);
  }
  /// @brief Optional description of what the test validates
  const ::flatbuffers::String *description() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DESCRIPTION);
  }
  /// @brief Tags for categorizing tests (e.g., "unit", "integration")
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *tags() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_TAGS);
  }
  /// @brief Expected test outcome (true = should pass, false = should fail)
  bool expected_to_pass() const {
    return GetField<uint8_t>(VT_EXPECTED_TO_PASS, 1) != 0;
  }
  /// @brief Optional author or creator of the test case
  const ::flatbuffers::String *author() const {
    return GetPointer<const ::flatbuffers::String *>(VT_AUTHOR);
  }
  /// @brief Version identifier for the test data format
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_TEST_NAME) &&
           verifier.VerifyString(test_name()) &&
           VerifyOffset(verifier, VT_DESCRIPTION) &&
           verifier.VerifyString(description()) &&
           VerifyOffset(verifier, VT_TAGS) &&
           verifier.VerifyVector(tags()) &&
           verifier.VerifyVectorOfStrings(tags()) &&
           VerifyField<uint8_t>(verifier, VT_EXPECTED_TO_PASS, 1) &&
           VerifyOffset(verifier, VT_AUTHOR) &&
           verifier.VerifyString(author()) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           verifier.EndTable();
  }
};

struct TestMetadataBuilder {
  typedef TestMetadata Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_test_name(::flatbuffers::Offset<::flatbuffers::String> test_name) {
    fbb_.AddOffset(TestMetadata::VT_TEST_NAME, test_name);
  }
  void add_description(::flatbuffers::Offset<::flatbuffers::String> description) {
    fbb_.AddOffset(TestMetadata::VT_DESCRIPTION, description);
  }
  void add_tags(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> tags) {
    fbb_.AddOffset(TestMetadata::VT_TAGS, tags);
  }
  void add_expected_to_pass(bool expected_to_pass) {
    fbb_.AddElement<uint8_t>(TestMetadata::VT_EXPECTED_TO_PASS, static_cast<uint8_t>(expected_to_pass), 1);
  }
  void add_author(::flatbuffers::Offset<::flatbuffers::String> author) {
    fbb_.AddOffset(TestMetadata::VT_AUTHOR, author);
  }
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(TestMetadata::VT_VERSION, version, 1);
  }
  explicit TestMetadataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TestMetadata> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TestMetadata>(end);
    fbb_.Required(o, TestMetadata::VT_TEST_NAME);
    return o;
  }
};

inline ::flatbuffers::Offset<TestMetadata> CreateTestMetadata(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> test_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> description = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> tags = 0,
    bool expected_to_pass = true,
    ::flatbuffers::Offset<::flatbuffers::String> author = 0,
    uint32_t version = 1) {
  TestMetadataBuilder builder_(_fbb);
  builder_.add_version(version);
  builder_.add_author(author);
  builder_.add_tags(tags);
  builder_.add_description(description);
  builder_.add_test_name(test_name);
  builder_.add_expected_to_pass(expected_to_pass);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TestMetadata> CreateTestMetadataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *test_name = nullptr,
    const char *description = nullptr,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *tags = nullptr,
    bool expected_to_pass = true,
    const char *author = nullptr,
    uint32_t version = 1) {
  auto test_name__ = test_name ? _fbb.CreateString(test_name) : 0;
  auto description__ = description ? _fbb.CreateString(description) : 0;
  auto tags__ = tags ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*tags) : 0;
  auto author__ = author ? _fbb.CreateString(author) : 0;
  return steamrot::CreateTestMetadata(
      _fbb,
      test_name__,
      description__,
      tags__,
      expected_to_pass,
      author__,
      version);
}

////////////////////////////////////////////////////////////
/// @brief Root table for test data configuration
///
/// This is the main container for test data. It's designed
/// to be extensible - new data types can be added as optional
/// fields without breaking existing tests.
////////////////////////////////////////////////////////////
struct TestDataConfig FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestDataConfigBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_METADATA = 4,
    VT_START_ENTITY_COLLECTION = 6,
    VT_EXPECTED_ENTITY_COLLECTION = 8,
    VT_GAME_RESOURCES = 10,
    VT_SCENE_RESOURCES = 12
  };
  /// @brief Metadata about this test case
  const steamrot::TestMetadata *metadata() const {
    return GetPointer<const steamrot::TestMetadata *>(VT_METADATA);
  }
  /// @brief Starting state entity collection for comparison tests
  /// If not provided, defaults to default-constructed EntityMemoryPool
  const steamrot::EntityCollection *start_entity_collection() const {
    return GetPointer<const steamrot::EntityCollection *>(VT_START_ENTITY_COLLECTION);
  }
  /// @brief Expected state entity collection for comparison tests
  const steamrot::EntityCollection *expected_entity_collection() const {
    return GetPointer<const steamrot::EntityCollection *>(VT_EXPECTED_ENTITY_COLLECTION);
  }
  /// @brief Resource data for test fixtures
  const steamrot::GameResourcesData *game_resources() const {
    return GetPointer<const steamrot::GameResourcesData *>(VT_GAME_RESOURCES);
  }
  const steamrot::SceneResourcesData *scene_resources() const {
    return GetPointer<const steamrot::SceneResourcesData *>(VT_SCENE_RESOURCES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_METADATA) &&
           verifier.VerifyTable(metadata()) &&
           VerifyOffset(verifier, VT_START_ENTITY_COLLECTION) &&
           verifier.VerifyTable(start_entity_collection()) &&
           VerifyOffset(verifier, VT_EXPECTED_ENTITY_COLLECTION) &&
           verifier.VerifyTable(expected_entity_collection()) &&
           VerifyOffset(verifier, VT_GAME_RESOURCES) &&
           verifier.VerifyTable(game_resources()) &&
           VerifyOffset(verifier, VT_SCENE_RESOURCES) &&
           verifier.VerifyTable(scene_resources()) &&
           verifier.EndTable();
  }
};

struct TestDataConfigBuilder {
  typedef TestDataConfig Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_metadata(::flatbuffers::Offset<steamrot::TestMetadata> metadata) {
    fbb_.AddOffset(TestDataConfig::VT_METADATA, metadata);
  }
  void add_start_entity_collection(::flatbuffers::Offset<steamrot::EntityCollection> start_entity_collection) {
    fbb_.AddOffset(TestDataConfig::VT_START_ENTITY_COLLECTION, start_entity_collection);
  }
  void add_expected_entity_collection(::flatbuffers::Offset<steamrot::EntityCollection> expected_entity_collection) {
    fbb_.AddOffset(TestDataConfig::VT_EXPECTED_ENTITY_COLLECTION, expected_entity_collection);
  }
  void add_game_resources(::flatbuffers::Offset<steamrot::GameResourcesData> game_resources) {
    fbb_.AddOffset(TestDataConfig::VT_GAME_RESOURCES, game_resources);
  }
  void add_scene_resources(::flatbuffers::Offset<steamrot::SceneResourcesData> scene_resources) {
    fbb_.AddOffset(TestDataConfig::VT_SCENE_RESOURCES, scene_resources);
  }
  explicit TestDataConfigBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TestDataConfig> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TestDataConfig>(end);
    fbb_.Required(o, TestDataConfig::VT_METADATA);
    return o;
  }
};

inline ::flatbuffers::Offset<TestDataConfig> CreateTestDataConfig(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::TestMetadata> metadata = 0,
    ::flatbuffers::Offset<steamrot::EntityCollection> start_entity_collection = 0,
    ::flatbuffers::Offset<steamrot::EntityCollection> expected_entity_collection = 0,
    ::flatbuffers::Offset<steamrot::GameResourcesData> game_resources = 0,
    ::flatbuffers::Offset<steamrot::SceneResourcesData> scene_resources = 0) {
  TestDataConfigBuilder builder_(_fbb);
  builder_.add_scene_resources(scene_resources);
  builder_.add_game_resources(game_resources);
  builder_.add_expected_entity_collection(expected_entity_collection);
  builder_.add_start_entity_collection(start_entity_collection);
  builder_.add_metadata(metadata);
  return builder_.Finish();
}

inline const steamrot::TestDataConfig *GetTestDataConfig(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::TestDataConfig>(buf);
}

inline const steamrot::TestDataConfig *GetSizePrefixedTestDataConfig(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::TestDataConfig>(buf);
}

inline bool VerifyTestDataConfigBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::TestDataConfig>(nullptr);
}

inline bool VerifySizePrefixedTestDataConfigBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::TestDataConfig>(nullptr);
}

inline void FinishTestDataConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::TestDataConfig> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTestDataConfigBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::TestDataConfig> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_TESTDATA_STEAMROT_H_
