// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_USERPREFERENCES_STEAMROT_H_
#define FLATBUFFERS_GENERATED_USERPREFERENCES_STEAMROT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace steamrot {

struct DisplayPreferences;
struct DisplayPreferencesBuilder;

struct AudioPreferences;
struct AudioPreferencesBuilder;

struct AccessibilityPreferences;
struct AccessibilityPreferencesBuilder;

struct UserPreferencesData;
struct UserPreferencesDataBuilder;

////////////////////////////////////////////////////////////
/// Display-related user preferences
/// Note: Window size/framerate are in GameResourcesData, not here
////////////////////////////////////////////////////////////
struct DisplayPreferences FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DisplayPreferencesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FULLSCREEN = 4,
    VT_VSYNC = 6
  };
  /// Fullscreen mode enabled
  bool fullscreen() const {
    return GetField<uint8_t>(VT_FULLSCREEN, 0) != 0;
  }
  /// VSync enabled
  bool vsync() const {
    return GetField<uint8_t>(VT_VSYNC, 1) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FULLSCREEN, 1) &&
           VerifyField<uint8_t>(verifier, VT_VSYNC, 1) &&
           verifier.EndTable();
  }
};

struct DisplayPreferencesBuilder {
  typedef DisplayPreferences Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_fullscreen(bool fullscreen) {
    fbb_.AddElement<uint8_t>(DisplayPreferences::VT_FULLSCREEN, static_cast<uint8_t>(fullscreen), 0);
  }
  void add_vsync(bool vsync) {
    fbb_.AddElement<uint8_t>(DisplayPreferences::VT_VSYNC, static_cast<uint8_t>(vsync), 1);
  }
  explicit DisplayPreferencesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DisplayPreferences> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DisplayPreferences>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DisplayPreferences> CreateDisplayPreferences(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool fullscreen = false,
    bool vsync = true) {
  DisplayPreferencesBuilder builder_(_fbb);
  builder_.add_vsync(vsync);
  builder_.add_fullscreen(fullscreen);
  return builder_.Finish();
}

////////////////////////////////////////////////////////////
/// Audio-related user preferences
////////////////////////////////////////////////////////////
struct AudioPreferences FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AudioPreferencesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MASTER_VOLUME = 4,
    VT_MUSIC_VOLUME = 6,
    VT_SFX_VOLUME = 8,
    VT_MUTED = 10
  };
  /// Master volume (0.0 - 1.0)
  float master_volume() const {
    return GetField<float>(VT_MASTER_VOLUME, 1.0f);
  }
  /// Music volume (0.0 - 1.0)
  float music_volume() const {
    return GetField<float>(VT_MUSIC_VOLUME, 0.8f);
  }
  /// Sound effects volume (0.0 - 1.0)
  float sfx_volume() const {
    return GetField<float>(VT_SFX_VOLUME, 1.0f);
  }
  /// Master mute state
  bool muted() const {
    return GetField<uint8_t>(VT_MUTED, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_MASTER_VOLUME, 4) &&
           VerifyField<float>(verifier, VT_MUSIC_VOLUME, 4) &&
           VerifyField<float>(verifier, VT_SFX_VOLUME, 4) &&
           VerifyField<uint8_t>(verifier, VT_MUTED, 1) &&
           verifier.EndTable();
  }
};

struct AudioPreferencesBuilder {
  typedef AudioPreferences Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_master_volume(float master_volume) {
    fbb_.AddElement<float>(AudioPreferences::VT_MASTER_VOLUME, master_volume, 1.0f);
  }
  void add_music_volume(float music_volume) {
    fbb_.AddElement<float>(AudioPreferences::VT_MUSIC_VOLUME, music_volume, 0.8f);
  }
  void add_sfx_volume(float sfx_volume) {
    fbb_.AddElement<float>(AudioPreferences::VT_SFX_VOLUME, sfx_volume, 1.0f);
  }
  void add_muted(bool muted) {
    fbb_.AddElement<uint8_t>(AudioPreferences::VT_MUTED, static_cast<uint8_t>(muted), 0);
  }
  explicit AudioPreferencesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AudioPreferences> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AudioPreferences>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AudioPreferences> CreateAudioPreferences(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float master_volume = 1.0f,
    float music_volume = 0.8f,
    float sfx_volume = 1.0f,
    bool muted = false) {
  AudioPreferencesBuilder builder_(_fbb);
  builder_.add_sfx_volume(sfx_volume);
  builder_.add_music_volume(music_volume);
  builder_.add_master_volume(master_volume);
  builder_.add_muted(muted);
  return builder_.Finish();
}

////////////////////////////////////////////////////////////
/// Accessibility-related user preferences (extensible)
////////////////////////////////////////////////////////////
struct AccessibilityPreferences FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AccessibilityPreferencesBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UI_SCALE = 4,
    VT_PREFERRED_FONT = 6
  };
  /// UI scale factor (1.0 = default)
  float ui_scale() const {
    return GetField<float>(VT_UI_SCALE, 1.0f);
  }
  /// Preferred font name (empty = use default)
  const ::flatbuffers::String *preferred_font() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PREFERRED_FONT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_UI_SCALE, 4) &&
           VerifyOffset(verifier, VT_PREFERRED_FONT) &&
           verifier.VerifyString(preferred_font()) &&
           verifier.EndTable();
  }
};

struct AccessibilityPreferencesBuilder {
  typedef AccessibilityPreferences Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_ui_scale(float ui_scale) {
    fbb_.AddElement<float>(AccessibilityPreferences::VT_UI_SCALE, ui_scale, 1.0f);
  }
  void add_preferred_font(::flatbuffers::Offset<::flatbuffers::String> preferred_font) {
    fbb_.AddOffset(AccessibilityPreferences::VT_PREFERRED_FONT, preferred_font);
  }
  explicit AccessibilityPreferencesBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AccessibilityPreferences> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AccessibilityPreferences>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AccessibilityPreferences> CreateAccessibilityPreferences(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float ui_scale = 1.0f,
    ::flatbuffers::Offset<::flatbuffers::String> preferred_font = 0) {
  AccessibilityPreferencesBuilder builder_(_fbb);
  builder_.add_preferred_font(preferred_font);
  builder_.add_ui_scale(ui_scale);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AccessibilityPreferences> CreateAccessibilityPreferencesDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float ui_scale = 1.0f,
    const char *preferred_font = nullptr) {
  auto preferred_font__ = preferred_font ? _fbb.CreateString(preferred_font) : 0;
  return steamrot::CreateAccessibilityPreferences(
      _fbb,
      ui_scale,
      preferred_font__);
}

////////////////////////////////////////////////////////////
/// Root table containing all user preferences
////////////////////////////////////////////////////////////
struct UserPreferencesData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UserPreferencesDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DISPLAY = 4,
    VT_AUDIO = 6,
    VT_ACCESSIBILITY = 8,
    VT_VERSION = 10
  };
  /// Display settings
  const steamrot::DisplayPreferences *display() const {
    return GetPointer<const steamrot::DisplayPreferences *>(VT_DISPLAY);
  }
  /// Audio settings
  const steamrot::AudioPreferences *audio() const {
    return GetPointer<const steamrot::AudioPreferences *>(VT_AUDIO);
  }
  /// Accessibility settings
  const steamrot::AccessibilityPreferences *accessibility() const {
    return GetPointer<const steamrot::AccessibilityPreferences *>(VT_ACCESSIBILITY);
  }
  /// Version number for migration support
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 1);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DISPLAY) &&
           verifier.VerifyTable(display()) &&
           VerifyOffset(verifier, VT_AUDIO) &&
           verifier.VerifyTable(audio()) &&
           VerifyOffset(verifier, VT_ACCESSIBILITY) &&
           verifier.VerifyTable(accessibility()) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           verifier.EndTable();
  }
};

struct UserPreferencesDataBuilder {
  typedef UserPreferencesData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_display(::flatbuffers::Offset<steamrot::DisplayPreferences> display) {
    fbb_.AddOffset(UserPreferencesData::VT_DISPLAY, display);
  }
  void add_audio(::flatbuffers::Offset<steamrot::AudioPreferences> audio) {
    fbb_.AddOffset(UserPreferencesData::VT_AUDIO, audio);
  }
  void add_accessibility(::flatbuffers::Offset<steamrot::AccessibilityPreferences> accessibility) {
    fbb_.AddOffset(UserPreferencesData::VT_ACCESSIBILITY, accessibility);
  }
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(UserPreferencesData::VT_VERSION, version, 1);
  }
  explicit UserPreferencesDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UserPreferencesData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UserPreferencesData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UserPreferencesData> CreateUserPreferencesData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<steamrot::DisplayPreferences> display = 0,
    ::flatbuffers::Offset<steamrot::AudioPreferences> audio = 0,
    ::flatbuffers::Offset<steamrot::AccessibilityPreferences> accessibility = 0,
    uint32_t version = 1) {
  UserPreferencesDataBuilder builder_(_fbb);
  builder_.add_version(version);
  builder_.add_accessibility(accessibility);
  builder_.add_audio(audio);
  builder_.add_display(display);
  return builder_.Finish();
}

inline const steamrot::UserPreferencesData *GetUserPreferencesData(const void *buf) {
  return ::flatbuffers::GetRoot<steamrot::UserPreferencesData>(buf);
}

inline const steamrot::UserPreferencesData *GetSizePrefixedUserPreferencesData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<steamrot::UserPreferencesData>(buf);
}

inline bool VerifyUserPreferencesDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<steamrot::UserPreferencesData>(nullptr);
}

inline bool VerifySizePrefixedUserPreferencesDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<steamrot::UserPreferencesData>(nullptr);
}

inline void FinishUserPreferencesDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::UserPreferencesData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedUserPreferencesDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<steamrot::UserPreferencesData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace steamrot

#endif  // FLATBUFFERS_GENERATED_USERPREFERENCES_STEAMROT_H_
