include "../entities/entities.fbs";
include "../assets/asset_config.fbs";
include "../core/scene_types.fbs";
include "../logic/logic_data.fbs";
include "scene_resources.fbs";

namespace steamrot;

table SceneInfoFbs{
    scene_id: string;
    scene_type: SceneType;
  }

table SceneDataFbs{
    scene_info: SceneInfoFbs;
    scene_resources: SceneResourcesFbs;
    asset_config: AssetConfigFbs;
    entity_collection: EntityCollectionFbs;
    logic_collection_data: LogicCollectionData;
  }

root_type SceneDataFbs;
