/////////////////////////////////////////////////
/// @file
/// @brief Declaration of EngineSnapshot struct
/////////////////////////////////////////////////

/////////////////////////////////////////////////
/// Preprocessor Directives
/////////////////////////////////////////////////
#pragma once

/////////////////////////////////////////////////
/// Headers
/////////////////////////////////////////////////
#include "containers.h"
#include "uuid.h"
#include <unordered_map>

namespace steamrot {

/////////////////////////////////////////////////
/// @class EngineSnapshot
/// @brief Container struct for a snapshot of the engine state
///
/// This struct is intended to hold all relevant data representing the state of
/// the engine, and is primarily designed for data driven testing purposes.
/// 
/// Captures state for multiple scenes per tick using scene UUIDs as keys.
/////////////////////////////////////////////////
struct EngineSnapshot {
  /////////////////////////////////////////////////
  /// @brief Map of scene UUID to EntityMemoryPool snapshots
  /// 
  /// Stores the entity state for each active scene at this tick.
  /// Keys are scene UUIDs generated by the engine at runtime.
  /////////////////////////////////////////////////
  std::unordered_map<uuids::uuid, EntityMemoryPool> scene_snapshots;
};
} // namespace steamrot
