if(EXISTS "/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/events/test_events_tests-b12d07c.cmake")
  include("/home/runner/work/SteamRot/SteamRot/_codeql_build_dir/tests/events/test_events_tests-b12d07c.cmake")
else()
  add_test(test_events_NOT_BUILT-b12d07c test_events_NOT_BUILT-b12d07c)
endif()
