add_subdirectory(assets)
add_subdirectory(display)
add_subdirectory(entity)
add_subdirectory(events)
add_subdirectory(error_loop)
add_subdirectory(scenes)
add_subdirectory(engine)
add_subdirectory(logger)
add_subdirectory(resources)
add_subdirectory(data_providers)
add_subdirectory(logic)
add_subdirectory(types)
add_subdirectory(context)


