
# Unit tests organized by subsystem
add_subdirectory(assets)
add_subdirectory(data_providers)
# add_subdirectory(display)
add_subdirectory(entity)
add_subdirectory(harness)
add_subdirectory(events)
add_subdirectory(logic)
add_subdirectory(logic/spatial_analysis)
add_subdirectory(logic/render)
add_subdirectory(matchers)
add_subdirectory(reporters)
add_subdirectory(scenes)
# add_subdirectory(engine)
add_subdirectory(types)
add_subdirectory(assets_for_tests)
